import type { QuizQuestion } from '@/types/content';

/**
 * Shoulder MRI pre/post knowledge assessment (primary-care sports-medicine audience).
 *
 * Matched PARALLEL FORMS (shared parallelId, parallel-pre / parallel-post): 11 pairs
 * across 8 blueprint domains, each mapped to its source module (moduleId). Single
 * best answer, management-focused. Authored + adversarially verified.
 */
export const shoulderPrePostQuizQuestions: QuizQuestion[] = [
  {
    id: "sh-orientation-search-1-pre",
    domain: "orientation-search",
    moduleId: "shoulder-mri-orientation",
    prePostMapping: "parallel-pre",
    parallelId: "sh-orientation-search-1",
    stem: "A fellow reviewing a shoulder MRI wants to assess the subscapularis tendon at its lesser-tuberosity insertion and confirm that the long head of the biceps tendon is seated within the bicipital groove. Which imaging plane is best suited for evaluating both of these structures together?",
    options: [{ key: "A", text: "Axial" }, { key: "B", text: "Oblique coronal" }, { key: "C", text: "Oblique sagittal" }, { key: "D", text: "Abduction-external-rotation (ABER) oblique" }],
    correctAnswer: "A",
    explanation: "The axial plane displays the subscapularis tendon in cross-section at its lesser-tuberosity insertion and shows the long head of biceps within the bicipital groove, making it the workhorse plane for both. The oblique coronal plane is optimized for the supraspinatus and superior labrum and the oblique sagittal plane for muscle bulk and the cuff arch in profile, so choosing either mismatches a structure to a non-optimal plane; the ABER view is a problem-solving sequence for anteroinferior labral lesions, not a routine plane for the groove and subscapularis.",
    cognitiveLevel: "apply",
  },
  {
    id: "sh-orientation-search-1-post",
    domain: "orientation-search",
    moduleId: "shoulder-mri-orientation",
    prePostMapping: "parallel-post",
    parallelId: "sh-orientation-search-1",
    stem: "During a systematic search, a fellow wants to grade fatty infiltration and muscle bulk of the supraspinatus and infraspinatus bellies (Goutallier/Warner assessment) on a shoulder MRI. Which plane is the standard reference for this evaluation?",
    options: [{ key: "A", text: "Axial" }, { key: "B", text: "Oblique coronal" }, { key: "C", text: "Oblique sagittal" }, { key: "D", text: "True (non-oblique) coronal" }],
    correctAnswer: "C",
    explanation: "The oblique sagittal plane (the 'Y' view, just medial to the glenoid) profiles the cuff muscle bellies within the supraspinatus and infraspinatus fossae, which is where fatty infiltration and atrophy are graded. The oblique coronal plane best depicts the supraspinatus tendon and footprint rather than muscle bulk, the axial plane is optimized for the subscapularis and biceps groove, and a true coronal is not angled to the scapular plane, so selecting those confuses tendon/insertion or non-aligned planes with the muscle-belly plane.",
    cognitiveLevel: "apply",
  },
  {
    id: "sh-rotator-cuff-1-pre",
    domain: "rotator-cuff",
    moduleId: "shoulder-rotator-cuff",
    prePostMapping: "parallel-pre",
    parallelId: "sh-rotator-cuff-1",
    stem: "A 52-year-old with chronic shoulder pain has an MRI showing a thickened supraspinatus tendon with diffuse intermediate (not fluid-bright) signal on the fat-saturated T2 images, but no focal fluid-bright defect reaching either the articular or bursal surface. What does this finding most likely represent?",
    options: [{ key: "A", text: "Articular-surface partial-thickness tear" }, { key: "B", text: "Tendinosis (intermediate-signal degeneration)" }, { key: "C", text: "Bursal-surface partial-thickness tear" }, { key: "D", text: "Full-thickness tear with joint-to-bursa communication" }],
    correctAnswer: "B",
    explanation: "Tendon thickening with intermediate (not fluid-bright) signal that does not reach a surface is the classic appearance of tendinosis, reflecting myxoid/mucoid degeneration rather than a fiber gap. A partial tear requires focal fluid-bright signal reaching the articular or bursal surface, and a full-thickness tear requires a fluid-bright defect spanning the entire tendon with joint-to-bursa communication; calling intermediate non-surfacing signal a 'tear' is the most common over-reading error.",
    cognitiveLevel: "analyze",
  },
  {
    id: "sh-rotator-cuff-1-post",
    domain: "rotator-cuff",
    moduleId: "shoulder-rotator-cuff",
    prePostMapping: "parallel-post",
    parallelId: "sh-rotator-cuff-1",
    stem: "A 60-year-old with weakness has an MRI showing a fluid-bright gap through the full thickness of the supraspinatus tendon, with high T2 signal continuous from the glenohumeral joint into the overlying subacromial-subdeltoid bursa. Which interpretation best fits this finding?",
    options: [{ key: "A", text: "Tendinosis (intermediate-signal degeneration)" }, { key: "B", text: "Intrasubstance partial-thickness tear" }, { key: "C", text: "Articular-surface partial-thickness tear" }, { key: "D", text: "Full-thickness tear with joint-to-bursa communication" }],
    correctAnswer: "D",
    explanation: "A fluid-bright defect spanning the entire tendon thickness with continuity of fluid signal between the joint and the subacromial-subdeltoid bursa defines a full-thickness tear. Tendinosis shows intermediate, non-fluid signal without a gap, and an articular-surface or intrasubstance partial tear involves only part of the tendon thickness and does not create joint-to-bursa communication, so those choices underestimate a defect that clearly traverses the whole tendon.",
    cognitiveLevel: "analyze",
  },
  {
    id: "sh-rotator-cuff-2-pre",
    domain: "rotator-cuff",
    moduleId: "shoulder-rotator-cuff",
    prePostMapping: "parallel-pre",
    parallelId: "sh-rotator-cuff-2",
    stem: "An overhead-throwing athlete has a partial supraspinatus tear. On the oblique coronal images, the fluid-bright defect reaches the deep (inferior) surface of the tendon at the footprint, while the superior (bursal) fibers remain intact. How is this partial tear best classified?",
    options: [{ key: "A", text: "Bursal-sided tear" }, { key: "B", text: "Intrasubstance (interstitial) tear" }, { key: "C", text: "Articular-sided (PASTA) tear" }, { key: "D", text: "Full-thickness tear" }],
    correctAnswer: "C",
    explanation: "A defect reaching the deep/articular surface at the footprint with intact bursal fibers is an articular-sided partial tear, the PASTA lesion (partial articular-sided supraspinatus tendon avulsion), which is the most common partial tear and typical in throwers. A bursal-sided tear reaches the superior surface, and an intrasubstance tear is confined within the tendon touching neither surface, so those answers misassign which surface the fluid contacts.",
    cognitiveLevel: "analyze",
  },
  {
    id: "sh-rotator-cuff-2-post",
    domain: "rotator-cuff",
    moduleId: "shoulder-rotator-cuff",
    prePostMapping: "parallel-post",
    parallelId: "sh-rotator-cuff-2",
    stem: "A 48-year-old laborer with impingement symptoms has a partial supraspinatus tear. On fat-saturated images the fluid-bright defect reaches the superior surface of the tendon abutting the subacromial-subdeltoid bursa, while the deep articular fibers at the footprint remain intact. What is the correct classification?",
    options: [{ key: "A", text: "Articular-sided (PASTA) tear" }, { key: "B", text: "Bursal-sided tear" }, { key: "C", text: "Intrasubstance (interstitial) tear" }, { key: "D", text: "Full-thickness tear" }],
    correctAnswer: "B",
    explanation: "A partial tear whose fluid-bright defect reaches the superior surface adjacent to the subacromial bursa, with intact deep articular fibers, is a bursal-sided tear, classically associated with extrinsic impingement. An articular-sided (PASTA) tear contacts the deep surface instead, and an intrasubstance tear reaches neither surface; choosing those reverses or ignores which surface the defect contacts.",
    cognitiveLevel: "analyze",
  },
  {
    id: "sh-rotator-cuff-3-pre",
    domain: "rotator-cuff",
    moduleId: "shoulder-rotator-cuff",
    prePostMapping: "parallel-pre",
    parallelId: "sh-rotator-cuff-3",
    stem: "A 67-year-old has a full-thickness supraspinatus tear. On the oblique sagittal images the supraspinatus muscle shows more fat than muscle (Goutallier grade 3-4), and on coronal images the tendon stump is retracted to the level of the glenoid. Which feature most strongly predicts poor reparability and should prompt earlier surgical discussion?",
    options: [{ key: "A", text: "Goutallier grade 3-4 fatty infiltration with retraction to the glenoid" }, { key: "B", text: "A small rim of reactive subacromial bursal fluid" }, { key: "C", text: "Mild tendinosis of the adjacent infraspinatus" }, { key: "D", text: "A type II (curved) acromion" }],
    correctAnswer: "A",
    explanation: "Advanced Goutallier 3-4 fatty infiltration combined with high-grade retraction (Patte stage III, to the glenoid) and muscle atrophy is largely irreversible and predicts poor healing and re-tear, so it argues for earlier surgical referral before further degeneration. Reactive bursal fluid, mild adjacent tendinosis, and acromial shape influence symptoms but are not the dominant reparability/prognosis drivers, so they are plausible but incorrect markers of irreparability.",
    cognitiveLevel: "analyze",
  },
  {
    id: "sh-rotator-cuff-3-post",
    domain: "rotator-cuff",
    moduleId: "shoulder-rotator-cuff",
    prePostMapping: "parallel-post",
    parallelId: "sh-rotator-cuff-3",
    stem: "A 65-year-old has a full-thickness infraspinatus and supraspinatus tear. The surgeon asks which single imaging feature most strongly predicts that a durable repair is unlikely and warrants earlier surgical discussion. Which feature carries that prognostic weight?",
    options: [{ key: "A", text: "A moderate subacromial-subdeltoid bursal effusion" }, { key: "B", text: "A type III (hooked) acromion on the oblique sagittal images" }, { key: "C", text: "Mild tendinosis of the intact subscapularis" }, { key: "D", text: "Goutallier grade 3-4 fatty infiltration with muscle atrophy and retraction to the glenoid" }],
    correctAnswer: "D",
    explanation: "Advanced Goutallier 3-4 fatty infiltration with muscle atrophy and high-grade (Patte III) retraction to the glenoid reflects poor muscle-tendon quality that is largely irreversible and predicts low healing and high re-tear rates, so it drives earlier surgical discussion. A bursal effusion is nonspecific, a hooked acromion relates to impingement risk rather than tendon reparability, and mild subscapularis tendinosis is incidental, so each is a real but non-dominant finding that does not determine reparability.",
    cognitiveLevel: "analyze",
  },
  {
    id: "sh-subscapularis-biceps-1-pre",
    domain: "subscapularis-biceps",
    moduleId: "shoulder-biceps-interval-ac",
    prePostMapping: "parallel-pre",
    parallelId: "sh-subscapularis-biceps-1",
    stem: "A 55-year-old has an MRI showing a tear of the upper subscapularis tendon at the lesser tuberosity. On the axial images the long head of the biceps tendon is no longer within the bicipital groove and instead lies medially, displaced over the torn subscapularis. This medial biceps displacement is best interpreted as which of the following?",
    options: [{ key: "A", text: "A normal variant biceps position seen with a shallow groove" }, { key: "B", text: "An indirect sign of a biceps pulley lesion associated with the subscapularis tear" }, { key: "C", text: "An isolated supraspinatus tear without pulley involvement" }, { key: "D", text: "Mucoid degeneration of the intra-articular biceps tendon" }],
    correctAnswer: "B",
    explanation: "The subscapularis tendon contributes to the medial wall of the biceps pulley/reflection, so an upper subscapularis tear frequently disrupts the pulley and allows the biceps to sublux medially out of the groove, a recognized indirect sign of subscapularis/pulley injury. A shallow groove alone does not displace a seated tendon over a torn subscapularis, supraspinatus tears do not explain medial biceps subluxation, and mucoid degeneration alters signal rather than position, so those distractors miss the pulley mechanism.",
    cognitiveLevel: "analyze",
  },
  {
    id: "sh-subscapularis-biceps-1-post",
    domain: "subscapularis-biceps",
    moduleId: "shoulder-biceps-interval-ac",
    prePostMapping: "parallel-post",
    parallelId: "sh-subscapularis-biceps-1",
    stem: "A fellow notices on axial images that the long head of the biceps tendon has subluxed medially and appears to lie deep to (medial to) the lesser tuberosity. Recognizing the anatomic relationship of the biceps pulley, which additional tendon should be scrutinized most closely for an associated tear?",
    options: [{ key: "A", text: "Infraspinatus" }, { key: "B", text: "Teres minor" }, { key: "C", text: "Subscapularis" }, { key: "D", text: "Supraspinatus" }],
    correctAnswer: "C",
    explanation: "The subscapularis tendon forms the medial sling of the biceps pulley, so medial subluxation of the biceps out of the groove should trigger close evaluation of the subscapularis, which is commonly torn in this pattern. The infraspinatus and teres minor are posterior cuff and do not stabilize the biceps medially, and an isolated supraspinatus tear does not produce medial biceps subluxation, so those choices overlook the pulley's medial anatomy.",
    cognitiveLevel: "analyze",
  },
  {
    id: "sh-labrum-slap-1-pre",
    domain: "labrum-slap",
    moduleId: "shoulder-labrum-instability",
    prePostMapping: "parallel-pre",
    parallelId: "sh-labrum-slap-1",
    stem: "A 24-year-old overhead athlete has an MR arthrogram for clicking and deep pain. At the superior labrum, contrast tracks into a cleft that is smooth, oriented medially, parallels the glenoid rim, and stops at the biceps anchor without lateral extension. Which interpretation is best supported?",
    options: [{ key: "A", text: "Type II SLAP tear" }, { key: "B", text: "Anterosuperior sublabral foramen" }, { key: "C", text: "Normal sublabral recess" }, { key: "D", text: "Bucket-handle labral tear" }],
    correctAnswer: "C",
    explanation: "A sublabral recess is a normal variant: a smooth, medially oriented cleft that parallels the glenoid and stops at the biceps anchor without lateral extension or irregular margins, exactly as described. A type II SLAP tear would show contrast extending laterally into the labral substance with irregular margins posterior to the anchor, and a bucket-handle tear shows a displaced labral fragment; calling this smooth medial recess a tear is the most common over-reading error, while a sublabral foramen is an anterosuperior (not superior-at-the-anchor) variant.",
    cognitiveLevel: "analyze",
  },
  {
    id: "sh-labrum-slap-1-post",
    domain: "labrum-slap",
    moduleId: "shoulder-labrum-instability",
    prePostMapping: "parallel-post",
    parallelId: "sh-labrum-slap-1",
    stem: "A 27-year-old pitcher has an MR arthrogram. At the superior labrum, gadolinium extends laterally into the labral substance with irregular margins and tracks posterior to the biceps anchor. Which interpretation is best supported?",
    options: [{ key: "A", text: "Normal sublabral recess" }, { key: "B", text: "Type II SLAP tear" }, { key: "C", text: "Normal sublabral foramen" }, { key: "D", text: "Mucoid degeneration of the labrum" }],
    correctAnswer: "B",
    explanation: "Lateral extension into the labral substance, irregular margins, and tracking posterior to the biceps anchor distinguish a SLAP tear from a normal recess, which is smooth, medially oriented, and ends at the anchor. A sublabral recess and a sublabral foramen are both smooth variants that follow the glenoid rather than extending irregularly into the labrum, so labeling this finding either of those is the classic benign-variant pitfall; mucoid degeneration produces ill-defined intrasubstance signal without a discrete margin-irregular contrast-filled cleft.",
    cognitiveLevel: "analyze",
  },
  {
    id: "sh-instability-1-pre",
    domain: "instability",
    moduleId: "shoulder-labrum-instability",
    prePostMapping: "parallel-pre",
    parallelId: "sh-instability-1",
    stem: "A 30-year-old with recurrent anterior dislocations has an MR arthrogram. The anteroinferior labroligamentous complex is displaced medially and 'rolled up' on the glenoid neck along an intact but stripped scapular periosteum. Which lesion does this describe?",
    options: [{ key: "A", text: "Bankart lesion, with a disrupted anterior scapular periosteum" }, { key: "B", text: "ALPSA lesion, with the complex rolled up medially on an intact stripped periosteum" }, { key: "C", text: "Perthes lesion, with an intact periosteum and a non-displaced labrum resynovialized in place" }, { key: "D", text: "HAGL lesion, with avulsion of the inferior glenohumeral ligament from the humerus" }],
    correctAnswer: "B",
    explanation: "ALPSA (anterior labroligamentous periosteal sleeve avulsion) is medial displacement of the labroligamentous sleeve along an intact but stripped periosteum, classically chronic/recurrent with the labrum 'rolled up' on the glenoid neck. A Bankart has a torn periosteum so the labrum is not held medially, a Perthes keeps the periosteum intact but the labrum stays anatomically positioned rather than rolled up medially, and a HAGL is a humeral-sided ligament avulsion rather than a labral lesion.",
    cognitiveLevel: "analyze",
  },
  {
    id: "sh-instability-1-post",
    domain: "instability",
    moduleId: "shoulder-labrum-instability",
    prePostMapping: "parallel-post",
    parallelId: "sh-instability-1",
    stem: "A 22-year-old has anterior instability. On MR arthrogram the inferior glenohumeral ligament is avulsed from its humeral neck attachment, the axillary pouch takes on a 'J' configuration, and contrast leaks extra-articularly on the humeral side. The anteroinferior labrum is intact. Which lesion is this?",
    options: [{ key: "A", text: "Bankart lesion, with anteroinferior labral avulsion from the glenoid" }, { key: "B", text: "GLAD lesion, with a glenolabral articular cartilage defect and intact ligaments" }, { key: "C", text: "Perthes lesion, with a non-displaced anteroinferior labral tear on an intact periosteum" }, { key: "D", text: "HAGL lesion, with humeral avulsion of the inferior glenohumeral ligament and a J-shaped axillary pouch" }],
    correctAnswer: "D",
    explanation: "A HAGL lesion is humeral-sided avulsion of the inferior glenohumeral ligament, producing a 'J-sign' of the axillary pouch and an extra-articular contrast leak on the humeral side, with the glenoid labrum intact. A Bankart and a Perthes are glenoid/labral-sided lesions and a GLAD is a glenolabral cartilage injury, so all three represent the classic pitfall of fixating on the glenoid side while missing the humeral-sided ligament avulsion; none produces a humeral contrast leak or a J-shaped pouch.",
    cognitiveLevel: "analyze",
  },
  {
    id: "sh-instability-2-pre",
    domain: "instability",
    moduleId: "shoulder-labrum-instability",
    prePostMapping: "parallel-pre",
    parallelId: "sh-instability-2",
    stem: "A 26-year-old has had four anterior dislocations. MRI suggests substantial anterior glenoid bone loss and a Hill-Sachs lesion that appears to engage. The surgeon wants precise osseous quantification to decide between an arthroscopic soft-tissue repair and a Latarjet. What is the most appropriate next step?",
    options: [{ key: "A", text: "Proceed to arthroscopic Bankart repair on clinical grounds alone" }, { key: "B", text: "Obtain a radionuclide bone scan of the glenoid rim" }, { key: "C", text: "Repeat MRI with intra-articular gadolinium to re-image the labrum" }, { key: "D", text: "Obtain CT to quantify glenoid bone loss and the Hill-Sachs track" }],
    correctAnswer: "D",
    explanation: "When MRI suggests significant glenoid bone loss (approaching ~20% or more) or an engaging/off-track Hill-Sachs, CT \u2014 often 3D with the humeral head digitally subtracted \u2014 best quantifies the osseous defect and drives the choice between soft-tissue repair and a bony procedure such as Latarjet. Proceeding to isolated Bankart repair ignores that high bone loss predicts soft-tissue-repair failure, a bone scan gives no quantification of bone loss, and an MR arthrogram characterizes soft tissue but underestimates osseous defects compared with CT.",
    cognitiveLevel: "apply",
  },
  {
    id: "sh-instability-2-post",
    domain: "instability",
    moduleId: "shoulder-labrum-instability",
    prePostMapping: "parallel-post",
    parallelId: "sh-instability-2",
    stem: "A 19-year-old collision-sport athlete has recurrent anterior dislocations. CT shows ~25% anterior glenoid bone loss and an off-track Hill-Sachs lesion. Based on these osseous findings, which surgical strategy is most appropriate?",
    options: [{ key: "A", text: "Isolated arthroscopic Bankart repair, the labrum being the primary stabilizer" }, { key: "B", text: "Nonoperative management with bracing and activity modification" }, { key: "C", text: "A bony augmentation procedure such as Latarjet to restore the deficient glenoid arc" }, { key: "D", text: "Arthroscopic capsular plication to retension the anterior capsule" }],
    correctAnswer: "C",
    explanation: "Critical glenoid bone loss (around 20-25% or more) with an off-track/engaging Hill-Sachs predicts high failure rates for soft-tissue repair, so a bony procedure such as Latarjet \u2014 which lengthens the glenoid arc and adds a sling effect \u2014 is favored. Isolated Bankart repair reflects the misconception that labral repair suffices despite bone loss, bracing wrongly assumes bone loss is irrelevant to recurrence, and capsular plication addresses soft tissue but does not restore the deficient bony track.",
    cognitiveLevel: "apply",
  },
  {
    id: "sh-capsule-adhesive-1-pre",
    domain: "capsule-adhesive",
    moduleId: "shoulder-arthritis-bursa-dontmiss",
    prePostMapping: "parallel-pre",
    parallelId: "sh-capsule-adhesive-1",
    stem: "A 54-year-old with diabetes has months of progressive global stiffness and a marked loss of passive external rotation. Which MRI finding most specifically supports adhesive capsulitis rather than a rotator cuff tear?",
    options: [{ key: "A", text: "Fluid-bright signal spanning the supraspinatus from articular to bursal surface" }, { key: "B", text: "Thickening and edema of the coracohumeral ligament and rotator interval with obliteration of the subcoracoid fat triangle" }, { key: "C", text: "Intermediate signal and thickening of the supraspinatus tendon without a surface defect" }, { key: "D", text: "Fluid in the subacromial-subdeltoid bursa" }],
    correctAnswer: "B",
    explanation: "Adhesive capsulitis shows soft-tissue thickening and edema at the rotator interval and coracohumeral ligament with loss of the normal subcoracoid fat triangle, plus axillary pouch/inferior capsule thickening \u2014 findings that explain the global loss of motion. Fluid-bright transmural supraspinatus signal describes a full-thickness cuff tear (the mimic to be excluded), intermediate non-surfacing tendon signal describes tendinosis, and bursal fluid is nonspecific and does not indicate capsulitis.",
    cognitiveLevel: "analyze",
  },
  {
    id: "sh-capsule-adhesive-1-post",
    domain: "capsule-adhesive",
    moduleId: "shoulder-arthritis-bursa-dontmiss",
    prePostMapping: "parallel-post",
    parallelId: "sh-capsule-adhesive-1",
    stem: "A 49-year-old has 4 months of painful shoulder stiffness limiting motion in all planes. MRI is ordered to distinguish adhesive capsulitis from a cuff problem. Which constellation of findings is most specific for adhesive capsulitis?",
    options: [{ key: "A", text: "Retraction of the supraspinatus to the glenoid with Goutallier grade 3 fatty infiltration" }, { key: "B", text: "A laterally extending superior labral contrast cleft with irregular margins" }, { key: "C", text: "Thickening and edema of the axillary pouch and inferior glenohumeral ligament with rotator-interval and coracohumeral ligament thickening" }, { key: "D", text: "Isolated subacromial-subdeltoid bursal fluid without capsular changes" }],
    correctAnswer: "C",
    explanation: "The specific MRI signature of adhesive capsulitis is thickening and edema of the axillary pouch/inferior glenohumeral ligament combined with rotator-interval and coracohumeral ligament thickening and obliteration of the subcoracoid fat triangle, often with capsular enhancement. Supraspinatus retraction with fatty infiltration describes a chronic cuff tear (the mimic), a laterally extending irregular superior labral cleft describes a SLAP tear, and isolated bursal fluid is nonspecific and does not establish capsulitis.",
    cognitiveLevel: "analyze",
  },
  {
    id: "sh-nerve-entrapment-1-pre",
    domain: "nerve-entrapment",
    moduleId: "shoulder-arthritis-bursa-dontmiss",
    prePostMapping: "parallel-pre",
    parallelId: "sh-nerve-entrapment-1",
    stem: "A 35-year-old volleyball player has posterior shoulder weakness. MRI shows a posterosuperior labral tear with a paralabral cyst extending into the spinoglenoid notch. Which additional finding best explains the weakness and should be reported?",
    options: [{ key: "A", text: "Denervation of both the supraspinatus and infraspinatus, from compression at the suprascapular notch" }, { key: "B", text: "Denervation of the deltoid, from axillary nerve compression in the quadrilateral space" }, { key: "C", text: "Denervation edema or fatty atrophy of the infraspinatus alone, from suprascapular nerve compression at the spinoglenoid notch" }, { key: "D", text: "Denervation of the subscapularis, from upper subscapular nerve involvement" }],
    correctAnswer: "C",
    explanation: "A cyst at the spinoglenoid notch compresses the suprascapular nerve after its branch to the supraspinatus has departed, so denervation is isolated to the infraspinatus (edema acutely, fatty atrophy chronically). Denervation of both muscles is the more proximal suprascapular-notch pattern, and deltoid or subscapularis denervation involves different nerves (axillary, subscapular) not affected by a spinoglenoid notch cyst; the teaching point is to look beyond the labrum to muscle denervation signal.",
    cognitiveLevel: "analyze",
  },
  {
    id: "sh-nerve-entrapment-1-post",
    domain: "nerve-entrapment",
    moduleId: "shoulder-arthritis-bursa-dontmiss",
    prePostMapping: "parallel-post",
    parallelId: "sh-nerve-entrapment-1",
    stem: "A 41-year-old has shoulder pain and weakness of both abduction and external rotation. MRI shows a paralabral cyst arising from a superior labral tear that extends medially into the suprascapular notch. Which pattern of muscle denervation do you most expect?",
    options: [{ key: "A", text: "Isolated infraspinatus denervation, the cyst lying distal to the supraspinatus branch" }, { key: "B", text: "Isolated teres minor denervation, from axillary nerve compression" }, { key: "C", text: "Isolated supraspinatus denervation, the cyst sparing the infraspinatus branch" }, { key: "D", text: "Denervation of both the supraspinatus and infraspinatus, the cyst compressing the suprascapular nerve at the suprascapular notch" }],
    correctAnswer: "D",
    explanation: "A cyst at the suprascapular notch compresses the nerve proximal to both motor branches, so both the supraspinatus and infraspinatus show denervation, matching the combined abduction and external-rotation weakness. Isolated infraspinatus denervation is the more distal spinoglenoid-notch pattern, isolated supraspinatus denervation inverts the anatomy because a proximal lesion cannot spare the infraspinatus, and teres minor denervation involves a different nerve; the key is to localize the cyst along the nerve's course.",
    cognitiveLevel: "analyze",
  },
  {
    id: "sh-postoperative-1-pre",
    domain: "postoperative",
    moduleId: "shoulder-arthritis-bursa-dontmiss",
    prePostMapping: "parallel-pre",
    parallelId: "sh-postoperative-1",
    stem: "Five months after supraspinatus repair, a patient has persistent pain. On fluid-sensitive images the repaired tendon shows intermediate-to-heterogeneous signal and mild thickening, with a little subacromial-subdeltoid bursal fluid and focal susceptibility artifact near the anchors. How should this be interpreted?",
    options: [{ key: "A", text: "Recurrent full-thickness tear, because persistent intratendinous signal indicates failure" }, { key: "B", text: "Recurrent full-thickness tear, because subacromial-subdeltoid bursal fluid confirms a gap" }, { key: "C", text: "Recurrent full-thickness tear, because anchor susceptibility artifact represents a tendon defect" }, { key: "D", text: "Expected postoperative change, because heterogeneous signal, mild bursal fluid, and anchor artifact are normal here" }],
    correctAnswer: "D",
    explanation: "Repaired cuff tendons normally remain thickened and heterogeneous with intermediate-to-increased signal for many months, and mild bursal fluid and anchor susceptibility artifact are expected, so none of these indicates failure. Options A, B, and C each reflect the common error of overcalling a recurrent tear from nonspecific postoperative signal, reactive bursal fluid, or hardware artifact; a recurrent full-thickness tear instead requires a fluid-bright gap spanning the tendon with fluid communication.",
    cognitiveLevel: "analyze",
  },
  {
    id: "sh-postoperative-1-post",
    domain: "postoperative",
    moduleId: "shoulder-arthritis-bursa-dontmiss",
    prePostMapping: "parallel-post",
    parallelId: "sh-postoperative-1",
    stem: "Seven months after rotator cuff repair, a patient has recurrent pain and weakness. On fluid-sensitive fat-saturated images there is a fluid-bright (fluid-equivalent) defect spanning the full thickness of the repaired tendon, with fluid communicating between the joint and the subacromial-subdeltoid bursa. Which interpretation is best supported?",
    options: [{ key: "A", text: "Recurrent full-thickness tear, because a fluid-bright gap spans the tendon with joint-to-bursa communication" }, { key: "B", text: "Expected postoperative change, because some increased intratendinous signal is normal after repair" }, { key: "C", text: "Expected postoperative change, because anchor susceptibility artifact mimics a defect" }, { key: "D", text: "Tendinosis of the repaired tendon, because the signal is intermediate rather than fluid-bright" }],
    correctAnswer: "A",
    explanation: "A fluid-bright (fluid-equivalent) defect spanning the full tendon thickness with fluid communication between the joint and the subacromial-subdeltoid bursa is the reliable sign of a recurrent full-thickness tear. Options B and C reflect the opposite error of dismissing a true fluid-bright gap as benign postoperative signal or artifact, and option D mischaracterizes the defect because the finding is fluid-equivalent, not the intermediate signal of tendinosis.",
    cognitiveLevel: "analyze",
  },
];
