export interface ModuleMetadata {
  id: string;
  number: number;
  title: string;
  subtitle: string;
  searchPatternStep: number | null;
  estimatedMinutes: number;
  topics: string[];
}

export const moduleRegistry: ModuleMetadata[] = [
  {
    id: 'mri-basics',
    number: 1,
    title: 'MRI Basics',
    subtitle: 'Planes, sequences, and common pitfalls',
    searchPatternStep: null,
    estimatedMinutes: 15,
    topics: [
      'Standard imaging planes: sagittal, coronal, axial',
      'Key sequences: T1, PD FS, T2',
      'What each sequence is best for (T1 for anatomy/fractures, PD FS for fluid/edema)',
      'Common artifacts and pitfalls (magic angle, truncation, motion)',
      'How to window/level for optimal viewing',
    ],
  },
  {
    id: 'anatomy',
    number: 2,
    title: 'Anatomy',
    subtitle: 'Compartments, landmarks, and what belongs where',
    searchPatternStep: null,
    estimatedMinutes: 20,
    topics: [
      'Three compartments: medial, lateral, patellofemoral',
      'Key bony landmarks and alignment',
      'Meniscal anatomy: horns, body, roots, attachments',
      'Cruciate and collateral ligament anatomy',
      'Normal variants that mimic pathology (popliteal hiatus, meniscofemoral ligaments, transverse ligament)',
      'Extensor mechanism anatomy',
    ],
  },
  {
    id: 'search-pattern-overview',
    number: 3,
    title: 'Search Pattern Overview',
    subtitle: 'The 7-step systematic approach',
    searchPatternStep: null,
    estimatedMinutes: 10,
    topics: [
      'Why systematic reading prevents missed findings',
      'Satisfaction of search: the most common cognitive error',
      'Overview of the 7-step search pattern',
      'How to build the pattern into daily workflow',
      'Anchor slice concept',
    ],
  },
  {
    id: 'bones-marrow',
    number: 4,
    title: 'Bones & Marrow',
    subtitle: 'Edema patterns, fractures, and alignment',
    searchPatternStep: 2,
    estimatedMinutes: 15,
    topics: [
      'Marrow edema patterns and injury mechanisms',
      'Pivot-shift contusion pattern (ACL injury)',
      'Dashboard contusion pattern (PCL injury)',
      'Patellar dislocation contusion pattern',
      'Insufficiency and stress fractures',
      'Alignment assessment: varus/valgus',
      'SIFK/SONK pattern recognition',
    ],
  },
  {
    id: 'cartilage-osteochondral',
    number: 5,
    title: 'Cartilage & Osteochondral',
    subtitle: 'Grading, OCD stability, SIFK, and loose bodies',
    searchPatternStep: 3,
    estimatedMinutes: 20,
    topics: [
      'Cartilage evaluation by compartment',
      'Cartilage grading systems',
      'OCD: location, sizing, and stability criteria',
      'Juvenile vs adult OCD differences',
      'MRI signs of fragment instability',
      'SIFK vs OCD vs AVN differentiation',
      'Loose body identification and reporting',
    ],
  },
  {
    id: 'menisci',
    number: 6,
    title: 'Menisci',
    subtitle: 'Tears, roots, ramp lesions, extrusion, and reporting',
    searchPatternStep: 4,
    estimatedMinutes: 25,
    topics: [
      'Meniscal signal grading (grade 1-3)',
      'Two-slice-touch rule for tear diagnosis',
      'Tear morphology: horizontal, vertical, radial, complex',
      'Root tears: identification and functional significance',
      'Ramp lesions: location and ACL association',
      'Bucket-handle tears: donor site, fragment, double PCL sign',
      'Meniscal extrusion measurement technique',
      'Parameniscal cysts',
      'Post-surgical meniscus evaluation',
    ],
  },
  {
    id: 'ligaments',
    number: 7,
    title: 'Ligaments',
    subtitle: 'ACL/PCL, MCL/LCL, PLC, and MPFL',
    searchPatternStep: 5,
    estimatedMinutes: 20,
    topics: [
      'ACL tear: primary and secondary signs',
      'ACL mucoid degeneration vs tear',
      'ACL graft evaluation',
      'PCL tear patterns and dashboard mechanism',
      'MCL injury grading and deep vs superficial layers',
      'LCL and posterolateral corner (PLC) anatomy and injury',
      'Posteromedial corner structures',
      'MPFL evaluation in patellar instability',
      'Combined injury patterns',
    ],
  },
  {
    id: 'extensor-synovium',
    number: 8,
    title: 'Extensor Mechanism & Synovium/Bursae',
    subtitle: "Quad/patellar tendon, Baker's cyst, and effusion",
    searchPatternStep: 6,
    estimatedMinutes: 15,
    topics: [
      'Quadriceps tendon tears: partial vs complete',
      'Patellar tendon pathology: tendinopathy vs tear',
      'Patellar fractures and bipartite patella',
      'Effusion characterization and lipohemarthrosis',
      "Baker's cyst: anatomy, rupture, mimics",
      'Bursitis patterns: prepatellar, infrapatellar, pes anserine',
      'Synovial pathology: PVNS, synovial chondromatosis',
    ],
  },
  {
    id: 'clinical-reporting',
    number: 9,
    title: 'Clinical Scenarios & Reporting',
    subtitle: 'Structured reports and impression templates',
    searchPatternStep: null,
    estimatedMinutes: 15,
    topics: [
      'Structured reporting framework for knee MRI',
      'Impression construction: diagnosis + associated injuries + osteochondral consequences',
      'Mechanism-based reporting templates',
      'Communicating management-changing findings',
      'Common referring clinician questions and how to address them',
      'When to recommend additional imaging or clinical correlation',
    ],
  },
  {
    id: 'top-10-dont-miss',
    number: 10,
    title: "Top 10 Don't Miss",
    subtitle: 'High-yield findings that change management',
    searchPatternStep: null,
    estimatedMinutes: 15,
    topics: [
      'Root tears with extrusion',
      'Ramp lesions in ACL injuries',
      'Bucket-handle tears (displaced fragment)',
      'Unstable OCD fragments',
      'PLC injuries (LCL + popliteus)',
      'MPFL tear with osteochondral fragment',
      'Lipohemarthrosis (occult fracture)',
      'Segond fracture (lateral capsular sign)',
      'Multiligament injury patterns',
      'Post-surgical re-tear vs expected appearance',
    ],
  },
];
