// Generated by scripts/export-medical-qa.mjs. Do not edit by hand.

export type MedicalQaRisk = "high" | "medium" | "standard";

export interface MedicalQaTotals {
  reviewItems: number;
  highRiskItems: number;
  sourceCheckItems: number;
  diagnostics: number;
  diagnosticErrors: number;
  diagnosticWarnings: number;
}

export interface MedicalQaCourseSummary {
  title: string;
  modules: number;
  cases: number;
  prePostQuizItems: number;
  normalPlanes: number;
  normalPlaneQuizItems: number;
  advancedItems: number;
  imageCaqItems: number;
  redFlags: number;
  reviewItems: number;
  highRiskItems: number;
  sourceCheckItems: number;
  diagnostics: number;
}

export interface MedicalQaReviewBreakdown {
  risks: Record<MedicalQaRisk, number>;
  itemTypes: Record<string, number>;
  sourceCheckByType: Record<string, number>;
}

export interface MedicalQaPriorityItem {
  courseId: string;
  courseTitle: string;
  itemType: string;
  itemId: string;
  section: string;
  title: string;
  risk: MedicalQaRisk;
  requiresSourceCheck: boolean;
  flags: string[];
  sourcePath: string;
  textPreview: string;
}

export const medicalQaGeneratedAt = "2026-06-23";

export const medicalQaTotals: MedicalQaTotals = {
  "reviewItems": 2714,
  "highRiskItems": 1337,
  "sourceCheckItems": 1557,
  "diagnostics": 0,
  "diagnosticErrors": 0,
  "diagnosticWarnings": 0
};

export const medicalQaCourseSummaries: Record<string, MedicalQaCourseSummary> = {
  "knee-mri": {
    "title": "UCLA Knee MRI Interpretation Course",
    "modules": 9,
    "cases": 13,
    "prePostQuizItems": 28,
    "normalPlanes": 4,
    "normalPlaneQuizItems": 45,
    "advancedItems": 36,
    "imageCaqItems": 6,
    "redFlags": 5,
    "reviewItems": 1319,
    "highRiskItems": 555,
    "sourceCheckItems": 654,
    "diagnostics": 0
  },
  "shoulder-mri": {
    "title": "Shoulder MRI for Primary Care Sports Medicine",
    "modules": 6,
    "cases": 8,
    "prePostQuizItems": 22,
    "normalPlanes": 4,
    "normalPlaneQuizItems": 46,
    "advancedItems": 34,
    "imageCaqItems": 6,
    "redFlags": 5,
    "reviewItems": 541,
    "highRiskItems": 182,
    "sourceCheckItems": 239,
    "diagnostics": 0
  },
  "hip-mri": {
    "title": "Hip MRI for Primary Care Sports Medicine",
    "modules": 8,
    "cases": 8,
    "prePostQuizItems": 24,
    "normalPlanes": 3,
    "normalPlaneQuizItems": 22,
    "advancedItems": 12,
    "imageCaqItems": 6,
    "redFlags": 5,
    "reviewItems": 483,
    "highRiskItems": 299,
    "sourceCheckItems": 338,
    "diagnostics": 0
  },
  "elbow-mri": {
    "title": "Elbow MRI for Primary Care Sports Medicine",
    "modules": 8,
    "cases": 8,
    "prePostQuizItems": 24,
    "normalPlanes": 3,
    "normalPlaneQuizItems": 7,
    "advancedItems": 10,
    "imageCaqItems": 6,
    "redFlags": 5,
    "reviewItems": 371,
    "highRiskItems": 301,
    "sourceCheckItems": 326,
    "diagnostics": 0
  }
};

export const medicalQaReviewBreakdown: Record<string, MedicalQaReviewBreakdown> = {
  "knee-mri": {
    "risks": {
      "high": 555,
      "medium": 99,
      "standard": 665
    },
    "itemTypes": {
      "course-overview": 1,
      "search-pattern-step": 7,
      "module-summary": 9,
      "module-common-mistake": 27,
      "module-topic": 68,
      "module-quiz": 63,
      "case-summary": 13,
      "case-model-report": 13,
      "case-teaching-point": 54,
      "case-search-finding": 91,
      "normal-tour-step": 39,
      "normal-plane-quiz": 45,
      "normal-structure-pearl": 22,
      "normal-structure-reading": 13,
      "normal-structure-correlate": 19,
      "normal-advanced-question": 36,
      "normal-image-caq": 6,
      "normal-cross-plane": 13,
      "pre-post-quiz": 28,
      "red-flag": 5,
      "surgical-correlate": 3,
      "daily-pearl": 30,
      "flashcard": 108,
      "review-registry-question": 505,
      "faq": 101
    },
    "sourceCheckByType": {
      "search-pattern-step": 4,
      "module-topic": 56,
      "module-common-mistake": 8,
      "module-summary": 5,
      "module-quiz": 40,
      "case-summary": 9,
      "case-model-report": 11,
      "case-teaching-point": 19,
      "case-search-finding": 22,
      "normal-tour-step": 9,
      "normal-plane-quiz": 12,
      "normal-structure-pearl": 6,
      "normal-structure-reading": 7,
      "normal-structure-correlate": 5,
      "normal-advanced-question": 28,
      "normal-image-caq": 6,
      "normal-cross-plane": 5,
      "pre-post-quiz": 21,
      "red-flag": 5,
      "surgical-correlate": 2,
      "daily-pearl": 11,
      "flashcard": 45,
      "review-registry-question": 284,
      "faq": 34
    }
  },
  "shoulder-mri": {
    "risks": {
      "high": 182,
      "medium": 57,
      "standard": 302
    },
    "itemTypes": {
      "course-overview": 1,
      "search-pattern-step": 8,
      "module-summary": 6,
      "module-common-mistake": 12,
      "module-topic": 29,
      "module-quiz": 30,
      "case-summary": 8,
      "case-model-report": 8,
      "case-teaching-point": 25,
      "case-search-finding": 64,
      "normal-tour-step": 34,
      "normal-plane-quiz": 46,
      "normal-structure-pearl": 18,
      "normal-structure-reading": 9,
      "normal-structure-correlate": 19,
      "normal-advanced-question": 34,
      "normal-image-caq": 6,
      "normal-cross-plane": 12,
      "pre-post-quiz": 22,
      "red-flag": 5,
      "surgical-correlate": 2,
      "reference-anatomySections": 5,
      "reference-measurementSections": 8,
      "daily-pearl": 30,
      "flashcard": 35,
      "review-registry-question": 65
    },
    "sourceCheckByType": {
      "search-pattern-step": 8,
      "module-topic": 15,
      "module-common-mistake": 2,
      "module-summary": 2,
      "module-quiz": 24,
      "case-search-finding": 13,
      "case-summary": 3,
      "case-model-report": 5,
      "case-teaching-point": 6,
      "normal-tour-step": 5,
      "normal-plane-quiz": 12,
      "normal-structure-pearl": 10,
      "normal-structure-reading": 4,
      "normal-structure-correlate": 3,
      "normal-advanced-question": 21,
      "normal-image-caq": 4,
      "normal-cross-plane": 3,
      "pre-post-quiz": 11,
      "red-flag": 3,
      "reference-anatomySections": 2,
      "reference-measurementSections": 8,
      "daily-pearl": 17,
      "flashcard": 17,
      "review-registry-question": 41
    }
  },
  "hip-mri": {
    "risks": {
      "high": 299,
      "medium": 39,
      "standard": 145
    },
    "itemTypes": {
      "course-overview": 1,
      "search-pattern-step": 7,
      "module-summary": 8,
      "module-common-mistake": 22,
      "module-topic": 44,
      "module-quiz": 24,
      "case-summary": 8,
      "case-model-report": 8,
      "case-teaching-point": 40,
      "case-search-finding": 56,
      "normal-tour-step": 25,
      "normal-plane-quiz": 22,
      "normal-structure-pearl": 13,
      "normal-structure-reading": 7,
      "normal-structure-correlate": 12,
      "normal-advanced-question": 12,
      "normal-image-caq": 6,
      "normal-cross-plane": 5,
      "pre-post-quiz": 24,
      "red-flag": 5,
      "surgical-correlate": 2,
      "reference-anatomySections": 5,
      "reference-measurementSections": 9,
      "daily-pearl": 30,
      "flashcard": 32,
      "review-registry-question": 56
    },
    "sourceCheckByType": {
      "course-overview": 1,
      "search-pattern-step": 7,
      "module-summary": 7,
      "module-common-mistake": 13,
      "module-topic": 43,
      "module-quiz": 23,
      "case-summary": 7,
      "case-model-report": 8,
      "case-teaching-point": 28,
      "case-search-finding": 25,
      "normal-tour-step": 7,
      "normal-plane-quiz": 4,
      "normal-structure-pearl": 5,
      "normal-structure-reading": 5,
      "normal-structure-correlate": 6,
      "normal-advanced-question": 8,
      "normal-image-caq": 5,
      "normal-cross-plane": 3,
      "pre-post-quiz": 24,
      "red-flag": 5,
      "surgical-correlate": 1,
      "reference-anatomySections": 4,
      "reference-measurementSections": 8,
      "daily-pearl": 18,
      "flashcard": 25,
      "review-registry-question": 48
    }
  },
  "elbow-mri": {
    "risks": {
      "high": 301,
      "medium": 25,
      "standard": 45
    },
    "itemTypes": {
      "course-overview": 1,
      "search-pattern-step": 8,
      "module-summary": 8,
      "module-common-mistake": 24,
      "module-topic": 40,
      "module-quiz": 24,
      "case-summary": 8,
      "case-model-report": 8,
      "case-teaching-point": 40,
      "case-search-finding": 64,
      "normal-tour-step": 19,
      "normal-plane-quiz": 7,
      "normal-structure-pearl": 11,
      "normal-structure-reading": 5,
      "normal-structure-correlate": 6,
      "normal-advanced-question": 10,
      "normal-image-caq": 6,
      "pre-post-quiz": 24,
      "red-flag": 5,
      "reference-anatomySections": 6,
      "reference-measurementSections": 12,
      "daily-pearl": 11,
      "review-registry-question": 24
    },
    "sourceCheckByType": {
      "search-pattern-step": 8,
      "module-summary": 8,
      "module-common-mistake": 20,
      "module-topic": 38,
      "module-quiz": 23,
      "case-summary": 8,
      "case-model-report": 8,
      "case-teaching-point": 33,
      "case-search-finding": 56,
      "normal-tour-step": 11,
      "normal-plane-quiz": 5,
      "normal-structure-pearl": 9,
      "normal-structure-reading": 5,
      "normal-structure-correlate": 4,
      "normal-advanced-question": 9,
      "normal-image-caq": 6,
      "pre-post-quiz": 24,
      "red-flag": 3,
      "reference-anatomySections": 5,
      "reference-measurementSections": 12,
      "daily-pearl": 8,
      "review-registry-question": 23
    }
  }
};

export const medicalQaPriorityItemCount = 1557;
