import type { QuizQuestion } from '@/types/content';

/**
 * Knee MRI pre/post knowledge assessment.
 *
 * Matched PARALLEL FORMS: every concept is tested both pre and post with an
 * equivalent-but-different vignette (shared parallelId, parallel-pre / parallel-post),
 * so growth is measurable per domain while resisting answer memorization. 14 pairs
 * across 9 blueprint domains, each mapped to its source module (moduleId). Single
 * best answer, application/analysis level. Authored and internally audited
 * against the course blueprint; formal faculty validation remains separate.
 */
export const prePostQuizQuestions: QuizQuestion[] = [
  {
    id: "kn-mri-basics-1-pre",
    domain: "mri-basics",
    moduleId: "mri-basics",
    prePostMapping: "parallel-pre",
    parallelId: "kn-mri-basics-1",
    stem: "A 24-year-old recreational runner has medial knee pain after ramping up mileage. On the coronal T1-weighted image a thin curvilinear low-signal line parallels the medial femoral condyle subchondral plate, and you suspect an early subchondral stress (fatigue) fracture. Which additional sequence best confirms the surrounding reactive marrow edema?",
    options: [{ key: "A", text: "Non-fat-saturated T2, where the edema blends in against the adjacent bright marrow fat" }, { key: "B", text: "Fat-saturated PD/T2, where edema is fluid-bright against suppressed fat" }, { key: "C", text: "Gradient-echo, which is the most sensitive sequence for marrow edema" }, { key: "D", text: "Non-fat-saturated T1, where the dark fracture line itself proves the edema" }],
    correctAnswer: "B",
    explanation: "Marrow edema is water-rich, so it is conspicuously fluid-bright on fluid-sensitive fat-saturated sequences (PD/T2 FS) where the normally bright fat signal is suppressed, maximizing contrast. Option D confuses the dark fracture line on T1 (which depicts the fracture, not the surrounding edema) with proof of edema, and option C reflects the common misconception that gradient-echo is sensitive for marrow edema when in fact susceptibility blooming makes it insensitive and unreliable here.",
    cognitiveLevel: "apply",
  },
  {
    id: "kn-mri-basics-1-post",
    domain: "mri-basics",
    moduleId: "mri-basics",
    prePostMapping: "parallel-post",
    parallelId: "kn-mri-basics-1",
    stem: "A 30-year-old presents after a twisting injury. A focal area of the lateral femoral condyle marrow is dark on T1, and you must decide whether it represents acute trauma-related edema or simply fatty (yellow) marrow. Which cross-sequence signal behavior confirms it is edema rather than fat?",
    options: [{ key: "A", text: "It follows fat: bright on T1 and dark on fat-saturated PD/T2" }, { key: "B", text: "It stays dark on fat-saturated PD/T2, matching cortical bone" }, { key: "C", text: "It enhances only after IV gadolinium and is otherwise occult on all unenhanced sequences" }, { key: "D", text: "It is dark on T1 yet becomes fluid-bright (high signal) on fat-saturated PD/T2" }],
    correctAnswer: "D",
    explanation: "True marrow edema contains increased water, so it is low on T1 and turns fluid-bright on fat-saturated PD/T2 while normal marrow fat is suppressed; this cross-sequence behavior is what distinguishes edema from fat. Option A describes fatty marrow, which follows fat on every sequence and is not edema, and option C reflects an over-reliance-on-contrast misconception, since marrow edema is readily seen on unenhanced fluid-sensitive sequences and does not require gadolinium.",
    cognitiveLevel: "apply",
  },
  {
    id: "kn-normal-variants-1-pre",
    domain: "normal-variants",
    moduleId: "anatomy",
    prePostMapping: "parallel-pre",
    parallelId: "kn-normal-variants-1",
    stem: "On a sagittal PD image you see an oblique low-signal band coursing just anterior and inferior to the anterior horn of the lateral meniscus, creating an apparent cleft. Before calling an anterior horn tear, what is the most likely explanation?",
    options: [{ key: "A", text: "Transverse (intermeniscal) ligament producing a pseudotear at its junction with the meniscus" }, { key: "B", text: "A radial tear of the lateral meniscus anterior horn" }, { key: "C", text: "Discoid meniscus with central degeneration" }, { key: "D", text: "Popliteus tendon within the popliteal hiatus" }],
    correctAnswer: "A",
    explanation: "The transverse intermeniscal ligament connects the anterior horns of the two menisci, and the fat-filled cleft at its attachment to the lateral anterior horn classically mimics a tear; tracing the band to the contralateral meniscus on adjacent slices confirms the variant. Option D (popliteus in the hiatus) mimics a POSTERIOR horn tear, not the anterior horn, and option B fails because a true radial tear would not be traceable as a continuous band crossing to the medial meniscus.",
    cognitiveLevel: "apply",
  },
  {
    id: "kn-normal-variants-1-post",
    domain: "normal-variants",
    moduleId: "anatomy",
    prePostMapping: "parallel-post",
    parallelId: "kn-normal-variants-1",
    stem: "On sagittal images a thin low-signal structure runs obliquely from the posterior horn of the lateral meniscus toward the medial femoral condyle, with a cleft at its meniscal origin that looks like a posterior horn tear. How do you confirm this is a normal variant?",
    options: [{ key: "A", text: "Trace it to its femoral attachment near the PCL, identifying a meniscofemoral ligament (Humphrey or Wrisberg)" }, { key: "B", text: "Confirm grade-3 signal reaching the surface on two matching images" }, { key: "C", text: "Note that the cleft disappears only on the coronal plane" }, { key: "D", text: "Identify the popliteus tendon passing through the popliteal hiatus" }],
    correctAnswer: "A",
    explanation: "The meniscofemoral ligaments of Humphrey (anterior to PCL) and Wrisberg (posterior to PCL) arise from the posterior horn of the lateral meniscus and insert on the medial femoral condyle; the fat cleft at their meniscal origin mimics a posterior horn tear, and tracing the band to its femoral attachment confirms the variant. Option B describes criteria for a true tear (the wrong conclusion here), and option D names a different lateral-meniscus pseudotear (popliteal hiatus) rather than the structure described.",
    cognitiveLevel: "analyze",
  },
  {
    id: "kn-search-reporting-1-pre",
    domain: "search-reporting",
    moduleId: "search-pattern-overview",
    prePostMapping: "parallel-pre",
    parallelId: "kn-search-reporting-1",
    stem: "You confirm a complete ACL tear on a young pivoting athlete's MRI. Applying a systematic search, which structure must you deliberately re-inspect next because missing it would change surgical planning?",
    options: [{ key: "A", text: "The posteromedial meniscocapsular junction for a ramp lesion and the posterior meniscal roots" }, { key: "B", text: "The quadriceps tendon insertion for tendinosis" }, { key: "C", text: "The prepatellar soft tissues for bursitis" }, { key: "D", text: "The proximal tibiofibular joint for a ganglion" }],
    correctAnswer: "A",
    explanation: "ACL tears are highly associated with ramp lesions at the posteromedial meniscocapsular junction and with posterior root tears, both of which are easily overlooked yet directly alter the surgeon's repair plan, so they belong in the directed post-ACL search and impression. Options C and D are real findings but are not management-changing companions of an ACL tear, and quadriceps tendinosis (option B) reflects satisfaction-of-search drift to an unrelated, low-yield structure.",
    cognitiveLevel: "apply",
  },
  {
    id: "kn-search-reporting-1-post",
    domain: "search-reporting",
    moduleId: "search-pattern-overview",
    prePostMapping: "parallel-post",
    parallelId: "kn-search-reporting-1",
    stem: "Your primary finding is a displaced bucket-handle tear of the medial meniscus with a fragment in the intercondylar notch. Following a disciplined search, what is the most important next structure to evaluate before finalizing the impression?",
    options: [{ key: "A", text: "The Hoffa fat pad for a focal ganglion cyst" }, { key: "B", text: "The iliotibial band for distal friction syndrome" }, { key: "C", text: "The ACL, because bucket-handle displacement is frequently associated with ACL insufficiency" }, { key: "D", text: "The pes anserine bursa for fluid" }],
    correctAnswer: "C",
    explanation: "A displaced fragment in the notch can mimic or obscure the ACL, and bucket-handle tears are commonly associated with ACL injury, so the disciplined reader must verify ACL integrity (and avoid the 'double-PCL'/pseudo-intact ACL pitfall) before the impression. Options B and D are incidental, non-management-changing checks that represent drifting away from the high-yield, directed search prompted by the primary finding.",
    cognitiveLevel: "apply",
  },
  {
    id: "kn-marrow-mechanism-1-pre",
    domain: "marrow-mechanism",
    moduleId: "bones-marrow",
    prePostMapping: "parallel-pre",
    parallelId: "kn-marrow-mechanism-1",
    stem: "A 19-year-old soccer player felt a pop while cutting. MRI shows kissing contusions at the lateral femoral condyle (sulcus terminalis region) and the posterolateral tibial plateau. Which ligament is most likely torn and should be scrutinized?",
    options: [{ key: "A", text: "Posterior cruciate ligament" }, { key: "B", text: "Anterior cruciate ligament" }, { key: "C", text: "Medial patellofemoral ligament" }, { key: "D", text: "Deep medial collateral ligament" }],
    correctAnswer: "B",
    explanation: "The pivot-shift mechanism can drive the lateral femoral condyle and posterolateral tibial plateau together, producing a characteristic contusion pattern that strongly supports ACL injury and should trigger direct ligament inspection. The PCL (option A) is associated with an anterior proximal tibia contusion after posteriorly directed force, and the MPFL (option C) belongs to the medial-patella/anterolateral-femoral-condyle pattern of transient lateral patellar dislocation. Marrow distribution is a mechanism clue, not independent proof of a ligament tear.",
    cognitiveLevel: "apply",
  },
  {
    id: "kn-marrow-mechanism-1-post",
    domain: "marrow-mechanism",
    moduleId: "bones-marrow",
    prePostMapping: "parallel-post",
    parallelId: "kn-marrow-mechanism-1",
    stem: "A teenager dislocated the patella while pivoting, then it spontaneously reduced. Which combination of marrow edema and the associated structure to evaluate fits this mechanism?",
    options: [{ key: "A", text: "Anterior proximal tibia edema; evaluate the PCL" }, { key: "B", text: "Lateral femoral condyle and posterolateral plateau edema; evaluate the ACL" }, { key: "C", text: "Medial patellar facet and anterolateral femoral condyle edema; evaluate the medial patellofemoral ligament" }, { key: "D", text: "Medial femoral condyle subchondral edema; evaluate the deep MCL" }],
    correctAnswer: "C",
    explanation: "Transient lateral patellar dislocation produces a characteristic contact-contusion pair at the medial patella and anterolateral lateral femoral condyle, so the medial patellofemoral stabilizers must be assessed separately along with the search for chondral or osteochondral fragments. Option B is the pivot-shift/ACL pattern and option A is the dashboard/PCL pattern, both representing different injury mechanisms.",
    cognitiveLevel: "analyze",
  },
  {
    id: "kn-marrow-mechanism-2-pre",
    domain: "marrow-mechanism",
    moduleId: "bones-marrow",
    prePostMapping: "parallel-pre",
    parallelId: "kn-marrow-mechanism-2",
    stem: "A 68-year-old woman has acute medial knee pain with no significant trauma. MRI shows a focal subchondral low-signal line paralleling the medial femoral condyle articular surface with surrounding marrow edema. Which feature best supports a subchondral insufficiency fracture (SIF) rather than a simple traumatic contusion?",
    options: [{ key: "A", text: "Diffuse, ill-defined marrow edema with no discrete subchondral line and an antecedent impact" }, { key: "B", text: "A discrete subchondral low-signal fracture line subjacent to the articular surface with adjacent edema, often without notable trauma" }, { key: "C", text: "Edema confined to the patella after a dashboard injury" }, { key: "D", text: "Bright T1 fatty signal replacing the subchondral bone" }],
    correctAnswer: "B",
    explanation: "A subchondral low-signal line or band parallel to the articular surface, surrounding edema-like signal, minimal trauma, and the typical location strongly support SIF. The fracture line can be subtle or occult, so its absence does not automatically prove a contusion; mechanism, morphology, and follow-up matter. Option D describes fatty marrow rather than an acute subchondral injury.",
    cognitiveLevel: "analyze",
  },
  {
    id: "kn-marrow-mechanism-2-post",
    domain: "marrow-mechanism",
    moduleId: "bones-marrow",
    prePostMapping: "parallel-post",
    parallelId: "kn-marrow-mechanism-2",
    stem: "A 70-year-old man develops sudden medial knee pain. MRI shows extensive medial femoral condyle marrow edema, a subchondral low-signal zone, and overlying articular-surface flattening. Which finding most supports the subchondral insufficiency fracture/SIF-with-osteonecrosis (SIF-ON) spectrum rather than systemic osteonecrosis?",
    options: [{ key: "A", text: "A subchondral fracture-line pattern with adjacent edema and surface deformity, without a serpiginous infarct margin" }, { key: "B", text: "A serpiginous geographic rim or double-line pattern demarcating an epiphyseal infarct" }, { key: "C", text: "Diffuse patchy marrow signal sparing the subchondral region" }, { key: "D", text: "Bilateral symmetric metaphyseal infarcts" }],
    correctAnswer: "A",
    explanation: "Many lesions formerly called SONK are now understood as subchondral insufficiency fracture, sometimes progressing to SIF with osteonecrosis and collapse. A subchondral fracture line with adjacent edema and surface deformity supports that spectrum; bone density may be normal or reduced. A serpentine infarct/double-line pattern favors systemic osteonecrosis.",
    cognitiveLevel: "analyze",
  },
  {
    id: "kn-menisci-1-pre",
    domain: "menisci",
    moduleId: "menisci",
    prePostMapping: "parallel-pre",
    parallelId: "kn-menisci-1",
    stem: "A 58-year-old presents after a deep squat with acute medial knee pain. Coronal PD fat-sat MRI shows a radial-oriented avulsion at the posterior root insertion of the medial meniscus, and on the coronal image the meniscal body is displaced 4 mm beyond the tibial margin. Functionally, how should this finding be characterized in your report?",
    options: [{ key: "A", text: "A stable degenerative intrasubstance change that requires no specific comment" }, { key: "B", text: "A peripheral longitudinal tear that is likely to heal given the vascular zone" }, { key: "C", text: "Loss of hoop-stress function with contact mechanics that can approach total medial meniscectomy in a complete medial-root model" }, { key: "D", text: "An isolated meniscocapsular separation without effect on load distribution" }],
    correctAnswer: "C",
    explanation: "A complete posterior medial root avulsion uncouples the circumferential collagen ring and markedly impairs hoop-stress transmission. Cadaveric medial-root data show contact mechanics approaching total medial meniscectomy, so the report should emphasize compartment overload while avoiding a blanket equivalence for every partial or lateral root abnormality.",
    cognitiveLevel: "analyze",
  },
  {
    id: "kn-menisci-1-post",
    domain: "menisci",
    moduleId: "menisci",
    prePostMapping: "parallel-post",
    parallelId: "kn-menisci-1",
    stem: "A 61-year-old reports a pop while gardening. Sagittal images show fluid signal cleaving the posterior horn of the medial meniscus at its tibial insertion, and on the coronal image the body extrudes 5 mm medial to the tibial plateau edge. How does this lesion alter the biomechanics of the involved compartment?",
    options: [{ key: "A", text: "It mildly stiffens the meniscus but preserves overall load transmission" }, { key: "B", text: "A complete posterior medial-root disruption can abolish hoop-stress transmission and approach total medial-meniscectomy contact mechanics in a cadaveric model" }, { key: "C", text: "It only affects rotational stability, leaving axial load distribution intact" }, { key: "D", text: "It produces a self-limited synovitis without measurable load redistribution" }],
    correctAnswer: "B",
    explanation: "Detachment of the posterior medial root releases circumferential fibers so axial load is no longer effectively converted into hoop stress. In a cadaveric model, peak contact pressure rose 25% with no detected difference from total medial meniscectomy, and repair restored pressure. This explains the biomechanical urgency, while actual treatment still depends on cartilage, alignment, chronicity, symptoms, and patient factors.",
    cognitiveLevel: "analyze",
  },
  {
    id: "kn-menisci-2-pre",
    domain: "menisci",
    moduleId: "menisci",
    prePostMapping: "parallel-pre",
    parallelId: "kn-menisci-2",
    stem: "A 47-year-old has lateral joint-line pain. On sequential sagittal PD fat-sat images the lateral meniscus shows a segment where the normal triangular meniscal tissue abruptly vanishes, leaving a 'ghost' of absent meniscus, and the coronal image shows a vertical cleft splitting the meniscus perpendicular to its free edge. Which tear morphology does this pattern indicate?",
    options: [{ key: "A", text: "A radial tear, with the 'cleft/ghost meniscus' sign reflecting a tear perpendicular to the circumferential fibers" }, { key: "B", text: "A peripheral longitudinal tear paralleling the meniscal circumference" }, { key: "C", text: "An intrasubstance (grade-2) degeneration not reaching the surface" }, { key: "D", text: "A meniscocapsular (ramp) separation at the posteromedial corner" }],
    correctAnswer: "A",
    explanation: "A radial tear runs perpendicular to the long axis of the meniscus, cutting across the circumferential collagen bundles; on the plane where the tear is in-plane the meniscus appears truncated or absent (the 'ghost meniscus' sign), with a vertical cleft on the orthogonal plane. Option B describes a longitudinal tear, which parallels rather than crosses the circumferential fibers and does not produce a ghost segment, and option C is intrasubstance signal that does not reach a surface, so it cannot produce a through-and-through cleft. Option D is a peripheral capsular separation on the medial side, a different location and morphology entirely.",
    cognitiveLevel: "analyze",
  },
  {
    id: "kn-menisci-2-post",
    domain: "menisci",
    moduleId: "menisci",
    prePostMapping: "parallel-post",
    parallelId: "kn-menisci-2",
    stem: "On a knee MRI, the medial meniscus body shows fluid-bright signal oriented perpendicular to its free margin on the coronal image, and on the adjacent sagittal slice the meniscus body looks shortened with a missing segment. The remaining meniscus is otherwise normal in position. How is this lesion best classified, and what is its key biomechanical consequence?",
    options: [{ key: "A", text: "A peripheral longitudinal tear; it usually preserves hoop-stress function" }, { key: "B", text: "A parameniscal cyst; it indicates a horizontal-cleavage tear with fluid tracking" }, { key: "C", text: "A bucket-handle tear; the fragment has displaced into the notch" }, { key: "D", text: "A radial tear extending to the free edge; it disrupts circumferential fibers and compromises hoop-stress distribution" }],
    correctAnswer: "D",
    explanation: "A cleft perpendicular to the free edge with a truncated/absent meniscal segment on the orthogonal plane is the signature of a radial tear. A complete or near-complete radial tear substantially disrupts circumferential fibers, compromises hoop-stress generation, and can promote extrusion and chondral overload; the biomechanical effect depends on tear width and location. The other options describe different morphology or displacement.",
    cognitiveLevel: "analyze",
  },
  {
    id: "kn-menisci-3-pre",
    domain: "menisci",
    moduleId: "menisci",
    prePostMapping: "parallel-pre",
    parallelId: "kn-menisci-3",
    stem: "A 19-year-old soccer player has a locked knee. Sagittal MRI shows a second low-signal band lying anterior and parallel to the posterior cruciate ligament within the intercondylar notch. The medial meniscus appears truncated. Which diagnosis does this fragment configuration indicate?",
    options: [{ key: "A", text: "A bucket-handle meniscal tear with the fragment displaced into the intercondylar notch" }, { key: "B", text: "A mucoid-degenerated PCL producing a thickened ligament" }, { key: "C", text: "A meniscal root tear with posterior extrusion of the meniscal body" }, { key: "D", text: "A torn meniscofemoral ligament of Wrisberg mimicking a second ligament" }],
    correctAnswer: "A",
    explanation: "A meniscal-sized fragment lying parallel and anterior to the PCL, together with a truncated parent meniscus, strongly supports a displaced bucket-handle tear and produces the 'double-PCL sign.' The sign should still be confirmed by tracing the fragment and donor site in multiple planes. Option B reflects the misconception that a doubled appearance equals PCL pathology, while option D confuses a normal meniscofemoral ligament with a displaced fragment; the Wrisberg ligament runs posterior to the PCL and is much thinner.",
    cognitiveLevel: "analyze",
  },
  {
    id: "kn-menisci-3-post",
    domain: "menisci",
    moduleId: "menisci",
    prePostMapping: "parallel-post",
    parallelId: "kn-menisci-3",
    stem: "Reviewing a knee MRI, you see grade-3 linear signal reaching the inferior articular surface of the medial meniscus posterior horn on two consecutive sagittal images, and the same defect is again visible reaching the surface on the coronal sequence. How should this be reported under the two-slice-touch criterion?",
    options: [{ key: "A", text: "Indeterminate, because surface signal must be confirmed on three or more contiguous slices" }, { key: "B", text: "A normal magic-angle artifact, since linear signal can be artifactual at the posterior horn" }, { key: "C", text: "A high-confidence meniscal tear, since surface-reaching signal is present on at least two matching images and corroborated in another plane" }, { key: "D", text: "An intrasubstance grade-2 signal that does not warrant a tear diagnosis" }],
    correctAnswer: "C",
    explanation: "Surface-reaching meniscal signal on at least two matching images gives high diagnostic confidence, and orthogonal-plane confirmation increases it further. The qualifying images need not be contiguous or even in the same plane. This is a confidence rule rather than an absolute gate, so morphology and artifacts still matter.",
    cognitiveLevel: "analyze",
  },
  {
    id: "kn-cartilage-osteochondral-1-pre",
    domain: "cartilage-osteochondral",
    moduleId: "cartilage-osteochondral",
    prePostMapping: "parallel-pre",
    parallelId: "kn-cartilage-osteochondral-1",
    stem: "A 34-year-old has a well-corticated osteochondral lesion of the lateral femoral condyle. On the fat-sat T2 image, a continuous line of fluid-equivalent high signal undercuts the entire fragment at its interface with the parent bone. Which conclusion about stability is best supported?",
    options: [{ key: "A", text: "The lesion is stable because the fragment retains its corticated margin" }, { key: "B", text: "The lesion is unstable, as a fluid-signal rim completely separating the fragment indicates loss of osseous bridging" }, { key: "C", text: "Stability cannot be assessed without intravenous contrast in every case" }, { key: "D", text: "The fluid line represents normal red-marrow signal and is reassuring" }],
    correctAnswer: "B",
    explanation: "A T2 fluid-equivalent rim that completely encircles the fragment interface signifies fluid tracking between fragment and donor site (loss of osseous continuity) and is a primary MRI sign of an unstable osteochondral lesion, alongside subchondral cysts, an overlying cartilage breach, and a displaced fragment. Option A is the classic trap that a corticated margin equals stability, whereas a complete high-signal rim outweighs that reassurance. Option D confuses bright fluid at the interface with normal hematopoietic marrow (which is intermediate, not fluid-bright), and C overstates the role of contrast, which is adjunctive rather than mandatory.",
    cognitiveLevel: "analyze",
  },
  {
    id: "kn-cartilage-osteochondral-1-post",
    domain: "cartilage-osteochondral",
    moduleId: "cartilage-osteochondral",
    prePostMapping: "parallel-post",
    parallelId: "kn-cartilage-osteochondral-1",
    stem: "A 13-year-old gymnast with open physes has a medial femoral condyle osteochondral lesion showing a thin band of high T2 signal at the fragment interface. There is no subchondral cyst, the overlying cartilage is intact, and the fragment is in situ. How should you interpret the interface signal in this patient?",
    options: [{ key: "A", text: "The interface signal indicates an unstable lesion warranting surgical fixation" }, { key: "B", text: "The lesion is stable because skeletally immature patients heal reliably" }, { key: "C", text: "Interface hyperintensity is less specific for instability in juveniles, so combine it with other signs and clinical findings before calling it unstable" }, { key: "D", text: "Open physes make MRI uninterpretable for osteochondral lesions" }],
    correctAnswer: "C",
    explanation: "In juvenile OCD with open physes, isolated T2 interface hyperintensity can reflect vascular granulation tissue and is poorly specific for instability. More specific juvenile findings include a fluid-equivalent rim plus an outer low-signal rim, multiple subchondral-plate breaks, multiple cysts or a cyst larger than about 5 mm, cartilage breach, or displacement. MRI remains central, but skeletal maturity changes interpretation.",
    cognitiveLevel: "analyze",
  },
  {
    id: "kn-cartilage-osteochondral-2-pre",
    domain: "cartilage-osteochondral",
    moduleId: "cartilage-osteochondral",
    prePostMapping: "parallel-pre",
    parallelId: "kn-cartilage-osteochondral-2",
    stem: "On a fat-suppressed PD image of the trochlea, you see a focal fluid-bright defect in the articular cartilage that extends through the full cartilage thickness down to, but not into, the subchondral bone plate. How should this chondral lesion be graded and reported?",
    options: [{ key: "A", text: "A superficial partial-thickness defect involving less than 50% of cartilage depth" }, { key: "B", text: "Subchondral marrow edema only, with the cartilage intact" }, { key: "C", text: "An osteochondral fracture, because the subchondral bone is involved" }, { key: "D", text: "A full-thickness chondral defect reaching the subchondral plate without bony involvement" }],
    correctAnswer: "D",
    explanation: "Fluid signal filling a defect that spans the entire cartilage depth down to the subchondral bone, with the bone plate intact, is a full-thickness chondral defect. Watch the grading system, because the two label this differently: it is modified Outerbridge grade IV (full-thickness loss with the plate exposed), but ICRS grade 3 \u2014 specifically ICRS 3C, 'down to but not through the subchondral bone' \u2014 because ICRS reserves grade 4 for a defect that breaches the subchondral plate into bone. Either way it remains a chondral, not osteochondral, injury. Option A undercalls a full-thickness defect as a partial one (<50% depth). Option C overcalls it as an osteochondral fracture; the subchondral bone is preserved here, distinguishing a pure chondral defect from an osteochondral one. Option B ignores the visible cartilage defect entirely.",
    cognitiveLevel: "apply",
  },
  {
    id: "kn-cartilage-osteochondral-2-post",
    domain: "cartilage-osteochondral",
    moduleId: "cartilage-osteochondral",
    prePostMapping: "parallel-post",
    parallelId: "kn-cartilage-osteochondral-2",
    stem: "A 27-year-old runner has knee pain. Fat-sat PD images show a focal cartilage irregularity at the medial femoral condyle where joint fluid undercuts a flap of cartilage, but the deepest fibers of cartilage and the underlying bone remain in contact with the plate. Which grade best describes this lesion?",
    options: [{ key: "A", text: "A partial-thickness chondral defect (cartilage flap/fissure) not extending to the subchondral bone" }, { key: "B", text: "A full-thickness defect with exposed subchondral bone" }, { key: "C", text: "An unstable osteochondral lesion with a displaced osseous fragment" }, { key: "D", text: "Normal cartilage with magic-angle artifact simulating a defect" }],
    correctAnswer: "A",
    explanation: "Fluid undercutting a cartilage flap while the deep cartilage fibers still abut the subchondral plate is a partial-thickness defect (a fissure or delamination flap), graded below full-thickness because the lesion does not reach bare bone. Option B overcalls the depth \u2014 there is no exposed subchondral bone \u2014 and option C invents an osseous fragment that is not present, confusing a chondral flap with an osteochondral lesion. Option D dismisses a genuine fluid-filled defect as magic-angle artifact, which would not show joint fluid tracking under a flap on fluid-sensitive sequences.",
    cognitiveLevel: "apply",
  },
  {
    id: "kn-cruciates-1-pre",
    domain: "cruciates",
    moduleId: "ligaments",
    prePostMapping: "parallel-pre",
    parallelId: "kn-cruciates-1",
    stem: "A 22-year-old soccer player has an acute non-contact pivoting injury. On the sagittal proton-density fat-saturated images, the radiologist wants to confirm a complete ACL tear using the most specific (primary) imaging criterion. Which finding most directly establishes the diagnosis?",
    options: [{ key: "A", text: "A curvilinear cortical avulsion at the lateral proximal tibia (Segond fragment)" }, { key: "B", text: "Anterior translation of the tibia relative to the femur of more than 7 mm" }, { key: "C", text: "Bone-marrow edema in the lateral femoral condyle and posterolateral tibial plateau" }, { key: "D", text: "Full-thickness discontinuity of the ACL fibers with intervening high T2 signal in the expected ligament course" }],
    correctAnswer: "D",
    explanation: "The direct/primary sign of a complete ACL tear is frank fiber discontinuity with abnormal T2 signal filling the expected ligament course; this is the most specific criterion. Anterior tibial translation (B) and pivot-shift kissing contusions in the lateral femoral condyle/posterolateral tibia (C) are secondary signs that support but do not by themselves prove a tear. A Segond fragment (A) is a lateral capsular avulsion strongly associated with ACL injury but is itself only an indirect marker, not the primary ligamentous sign.",
    cognitiveLevel: "analyze",
  },
  {
    id: "kn-cruciates-1-post",
    domain: "cruciates",
    moduleId: "ligaments",
    prePostMapping: "parallel-post",
    parallelId: "kn-cruciates-1",
    stem: "A 30-year-old basketball player landed awkwardly and felt a pop. On MRI the radiologist must decide which single finding constitutes the direct (primary) evidence of a complete ACL tear rather than a supportive secondary sign. Which observation provides that direct evidence?",
    options: [{ key: "A", text: "A deep lateral femoral notch (terminal sulcus) deeper than 1.5 mm" }, { key: "B", text: "Buckling of the PCL into an acute angulated (wavy) configuration" }, { key: "C", text: "Uncovering of the posterior horn of the lateral meniscus by the tibia" }, { key: "D", text: "Complete absence of intact ACL fibers spanning the notch with edematous signal replacing the ligament" }],
    correctAnswer: "D",
    explanation: "Direct visualization of absent/discontinuous ACL fibers replaced by edematous signal across the notch is the primary sign that defines a complete tear. A deep lateral femoral notch (A), a buckled PCL (B), and posterior uncovering of the lateral meniscus (C) are all secondary signs reflecting anterior tibial translation; trainees often over-rely on these, but they only suggest ACL incompetence and can occur with chronic laxity, so they cannot independently establish an acute complete tear.",
    cognitiveLevel: "analyze",
  },
  {
    id: "kn-cruciates-2-pre",
    domain: "cruciates",
    moduleId: "ligaments",
    prePostMapping: "parallel-pre",
    parallelId: "kn-cruciates-2",
    stem: "A 48-year-old runner has chronic vague posterior knee pain with no instability on exam. MRI shows a thickened ACL with intermediate T2 signal interspersed between intact, continuous, well-tensioned fibers, giving a striated appearance, and there is no anterior tibial translation. What is the most likely diagnosis?",
    options: [{ key: "A", text: "Acute complete ACL tear" }, { key: "B", text: "Chronic partial-thickness ACL tear with fiber retraction" }, { key: "C", text: "Mucoid degeneration of the ACL" }, { key: "D", text: "ACL ganglion cyst causing fiber rupture" }],
    correctAnswer: "C",
    explanation: "Mucoid degeneration produces a thickened, T2-hyperintense ACL with preserved, continuous, taut fibers \u2014 the classic 'celery stalk' appearance \u2014 and no secondary signs of instability, exactly as described. An acute complete tear (A) shows fiber discontinuity and translation, which are absent here. A partial tear with retraction (B) would show some disrupted fibers; the hallmark of mucoid degeneration is that the fibers remain intact, which is the point trainees most often miss when they overcall a tear. A ganglion (D) is a discrete cyst, not diffuse intrasubstance striation, and does not by itself rupture fibers.",
    cognitiveLevel: "apply",
  },
  {
    id: "kn-cruciates-2-post",
    domain: "cruciates",
    moduleId: "ligaments",
    prePostMapping: "parallel-post",
    parallelId: "kn-cruciates-2",
    stem: "A 53-year-old golfer reports an aching knee with a sense of fullness on deep flexion but a stable Lachman test. MRI demonstrates an enlarged ACL of increased T2 signal in which the individual fascicles remain continuous and longitudinally oriented, with no bone bruise and a normal tibiofemoral relationship. Which interpretation is correct?",
    options: [{ key: "A", text: "Complete mid-substance ACL tear with the empty-notch sign" }, { key: "B", text: "Mucoid degeneration of the ACL, not a tear" }, { key: "C", text: "High-grade partial ACL tear involving the anteromedial bundle" }, { key: "D", text: "Acute interstitial ACL sprain with intrasubstance hemorrhage" }],
    correctAnswer: "B",
    explanation: "Continuous, longitudinally oriented fibers with diffuse T2 signal (the 'celery stalk') and absent secondary signs in a clinically stable knee indicate mucoid degeneration rather than a tear. A complete tear (A) requires fiber discontinuity and an empty notch, which are absent. A high-grade partial tear (C) would disrupt some fascicles and often correlate with laxity; preserved continuity argues against it. An acute interstitial sprain (D) typically accompanies trauma and bone-marrow edema, which this chronic, atraumatic, bruise-free case lacks \u2014 the common error is mistaking benign mucoid signal for a tear.",
    cognitiveLevel: "analyze",
  },
  {
    id: "kn-collateral-corner-1-pre",
    domain: "collateral-corner",
    moduleId: "ligaments",
    prePostMapping: "parallel-pre",
    parallelId: "kn-collateral-corner-1",
    stem: "A 25-year-old skier has an acute pivoting injury (internal rotation with varus stress). MRI shows a curvilinear bony fragment avulsed from the lateral margin of the proximal tibia just below the joint line. Recognizing this finding should most prompt the radiologist to scrutinize which structure?",
    options: [{ key: "A", text: "The medial patellofemoral ligament" }, { key: "B", text: "The quadriceps tendon insertion" }, { key: "C", text: "The pes anserinus tendons" }, { key: "D", text: "The anterior cruciate ligament" }],
    correctAnswer: "D",
    explanation: "The described fragment is a Segond fracture, an avulsion of the lateral capsular/anterolateral ligament complex that carries a very high association with ACL tears (and often meniscal injury); seeing it mandates a careful look at the ACL. The quadriceps tendon (B) and pes anserinus (C) are unrelated to this lateral capsular avulsion. The MPFL (A) is implicated in patellar dislocation, a different mechanism; trainees sometimes confuse the lateral Segond avulsion with patellofemoral injuries, but the Segond's key teaching point is its ACL association.",
    cognitiveLevel: "apply",
  },
  {
    id: "kn-collateral-corner-1-post",
    domain: "collateral-corner",
    moduleId: "ligaments",
    prePostMapping: "parallel-post",
    parallelId: "kn-collateral-corner-1",
    stem: "A 28-year-old footballer sustained a pivoting injury. Coronal MRI reveals a thin vertically oriented cortical avulsion fragment along the lateral aspect of the proximal tibia at the site of the anterolateral capsular attachment. Identifying this fragment should raise the highest suspicion for concurrent injury of which structure?",
    options: [{ key: "A", text: "The anterior cruciate ligament" }, { key: "B", text: "The posterior cruciate ligament" }, { key: "C", text: "The patellar tendon" }, { key: "D", text: "The iliotibial band proximal origin" }],
    correctAnswer: "A",
    explanation: "This is a Segond fracture \u2014 a lateral capsular avulsion \u2014 and its principal clinical significance is the strong association with an ACL tear (plus frequent meniscal tears), so the ACL is the priority for further evaluation. A PCL avulsion (B) is a posterior/medial mechanism, not this lateral fragment. The patellar tendon (C) attaches at the tibial tubercle anteriorly, not the lateral capsular margin. The ITB (D) is sometimes invoked because of its lateral location, but the avulsed structure here is the anterolateral capsule/ligament, whose recognized companion injury is the ACL.",
    cognitiveLevel: "apply",
  },
  {
    id: "kn-extensor-synovium-1-pre",
    domain: "extensor-synovium",
    moduleId: "extensor-synovium",
    prePostMapping: "parallel-pre",
    parallelId: "kn-extensor-synovium-1",
    stem: "A 58-year-old man could not extend his knee after stumbling. Sagittal MRI shows a full-thickness gap with fluid signal in the tendon immediately superior to the superior pole of the patella, and the patella sits abnormally low. Which diagnosis best fits these findings?",
    options: [{ key: "A", text: "Quadriceps tendon rupture with patella baja" }, { key: "B", text: "Patellar tendon rupture with patella alta" }, { key: "C", text: "Quadriceps tendinosis without a tear" }, { key: "D", text: "Patellar tendon rupture with patella baja" }],
    correctAnswer: "A",
    explanation: "A defect just above the superior patellar pole localizes to the quadriceps tendon; loss of the proximal extensor restraint lets the patellar tendon pull the patella inferiorly, producing patella baja. Patellar tendon rupture (B, D) occurs below the inferior pole and produces patella alta because the unopposed quadriceps retracts the patella superiorly \u2014 so 'patellar tendon with baja' (D) is internally inconsistent. Tendinosis (C) shows thickening and intermediate signal without a full-thickness fluid-filled gap and would not cause inability to extend; mixing up the tendon involved and the resulting patellar position is the classic trainee error.",
    cognitiveLevel: "analyze",
  },
  {
    id: "kn-extensor-synovium-1-post",
    domain: "extensor-synovium",
    moduleId: "extensor-synovium",
    prePostMapping: "parallel-post",
    parallelId: "kn-extensor-synovium-1",
    stem: "A 34-year-old basketball player felt a pop while jumping and cannot actively straighten the knee. Sagittal MRI shows a full-thickness fluid-filled gap in the tendon just distal to the inferior pole of the patella, and the patella is positioned abnormally high. Which diagnosis best accounts for these findings?",
    options: [{ key: "A", text: "Quadriceps tendon rupture with patella alta" }, { key: "B", text: "Patellar tendinosis without a discrete tear" }, { key: "C", text: "Patellar tendon rupture with patella alta" }, { key: "D", text: "Quadriceps tendon rupture with patella baja" }],
    correctAnswer: "C",
    explanation: "A full-thickness gap just below the inferior patellar pole is a patellar tendon rupture; with the distal tether lost, the intact quadriceps retracts the patella upward, yielding patella alta. A quadriceps rupture (A, D) involves the tendon above the superior pole and produces patella baja, so 'quadriceps with alta' (A) is internally inconsistent. Patellar tendinosis (B) shows fusiform thickening with intermediate signal and intact fibers, not a fluid-filled discontinuity, and preserves active extension; confusing which tendon failed and the direction the patella migrates is the high-yield distinction being tested.",
    cognitiveLevel: "analyze",
  },
];
