import type { QuizQuestion } from '@/types/content';

/**
 * Hip MRI pre/post knowledge assessment (primary-care sports-medicine audience).
 *
 * Matched PARALLEL FORMS (shared parallelId): 12 parallel pairs across the 8 blueprint
 * domains -> a 12-item pre form and a 12-item post form that share NO items, so the
 * formative pre-results feedback can never leak a post answer. (The four highest-stakes
 * domains carry a second pair.) Single best answer, application/analysis level,
 * management-focused. Each post item sits at a different answer position than its pre
 * mate; no answer key dominates either form.
 * Authored + adversarially verified (MSK accuracy / psychometric equivalence / test-wiseness).
 */
export const hipPrePostQuizQuestions: QuizQuestion[] = [
  {
    id: "hip-anatomy-pre",
    domain: "hip-anatomy",
    moduleId: "hip-anatomy",
    prePostMapping: "parallel-pre",
    parallelId: "hip-anatomy-sublabral-variant",
    stem: "A 28-year-old has nonspecific anterior groin discomfort. MRI shows a smooth, linear high-signal cleft at the posteroinferior chondrolabral junction that follows the labral margin without displacement, blunting, or an adjacent paralabral cyst, and the labrum is otherwise normal in size and shape. What is the most appropriate management implication of this finding?",
    options: [{ key: "A", text: "Refer for arthroscopic labral repair given a displaced bucket-handle tear" }, { key: "B", text: "Order urgent aspiration for suspected paralabral cyst causing nerve compression" }, { key: "C", text: "Treat as a likely normal sublabral sulcus variant; correlate clinically rather than refer for surgery" }, { key: "D", text: "Escalate to oncology workup for a labral-based soft-tissue mass" }],
    correctAnswer: "C",
    explanation:
      "A smooth linear cleft following the labral margin without displacement, blunting, or a paralabral cyst is most consistent with a normal sublabral sulcus/recess variant and should be correlated clinically, not taken to surgery. The location is important: sublabral sulci/recesses are most accepted as normal variants posteroinferiorly and at the anteroinferior junction, whereas a true cleft at the anterosuperior junction is the site where pathologic tears predominate and should not be casually dismissed as a variant. A bucket-handle tear (A) shows a displaced fragment, which is absent. There is no cyst to aspirate (B). A normal-shaped labrum with a thin cleft is not a mass (D).",
    cognitiveLevel: "analyze",
  },
  {
    id: "hip-anatomy-post",
    domain: "hip-anatomy",
    moduleId: "hip-anatomy",
    prePostMapping: "parallel-post",
    parallelId: "hip-anatomy-sublabral-variant",
    stem: "A 35-year-old recreational athlete has mild intermittent groin ache. MRI demonstrates a thin, regular high-signal line at the posteroinferior chondrolabral junction paralleling the labral base, with a triangular labrum of normal contour, no fragment displacement, and no surrounding cyst. How should this finding most appropriately direct management?",
    options: [{ key: "A", text: "Diagnose a full-thickness radial labral tear and refer for reconstruction" }, { key: "B", text: "Interpret as a normal sublabral recess; manage symptoms clinically without surgical referral" }, { key: "C", text: "Recommend MR arthrography solely to drain an associated paralabral cyst" }, { key: "D", text: "Initiate a marrow-replacement tumor protocol for a labral lesion" }],
    correctAnswer: "B",
    explanation:
      "A thin regular line at the posteroinferior chondrolabral junction paralleling the labral base with a normally contoured labrum and no cyst or displacement indicates a normal sublabral recess variant; manage clinically. Location matters: a posteroinferior/inferior cleft is a recognized normal-variant site, in contrast to the anterosuperior junction where most true symptomatic tears occur and a cleft cannot be safely called a variant. A radial tear (A) disrupts and irregularly clefts the labrum, not seen here. There is no cyst to drain (C), and a normal-appearing labrum is not a tumor (D).",
    cognitiveLevel: "analyze",
  },
  {
    id: "hip-bones-stress-pre",
    domain: "hip-bones-stress",
    moduleId: "hip-bones-stress",
    prePostMapping: "parallel-pre",
    parallelId: "hip-bones-tension-vs-compression",
    stem: "A 30-year-old marathoner has 2 weeks of groin pain. MRI shows marrow edema in the femoral neck with a linear T1-hypointense fracture line along the superolateral (tension) cortex extending partway across the neck. What is the most appropriate management?",
    options: [{ key: "A", text: "Allow continued running with a 10% weekly mileage reduction and recheck in 6 weeks" }, { key: "B", text: "Make the patient non-weight-bearing and obtain urgent orthopedic surgical referral" }, { key: "C", text: "Start protected weight-bearing with a cane and routine clinic follow-up in 3 months" }, { key: "D", text: "Inject the hip with corticosteroid to control pain and resume training" }],
    correctAnswer: "B",
    explanation:
      "A tension-side (superolateral) femoral neck stress fracture is at high risk of completion and displacement and is treated as a surgical emergency with non-weight-bearing and urgent referral. Continued running (A), partial weight-bearing with routine follow-up (C), or steroid injection (D) all risk catastrophic completion of the fracture.",
    cognitiveLevel: "apply",
  },
  {
    id: "hip-bones-stress-post",
    domain: "hip-bones-stress",
    moduleId: "hip-bones-stress",
    prePostMapping: "parallel-post",
    parallelId: "hip-bones-tension-vs-compression",
    stem: "A 26-year-old triathlete reports 3 weeks of groin pain. MRI reveals femoral neck marrow edema with a short fracture line along the inferomedial (compression) cortex and no cortical break or displacement. What is the most appropriate management?",
    options: [{ key: "A", text: "Immediate operative fixation that day as a surgical emergency" }, { key: "B", text: "Continue full training with anti-inflammatories and no imaging follow-up" }, { key: "C", text: "Protected weight-bearing with activity modification and close outpatient orthopedic follow-up" }, { key: "D", text: "Same-day corticosteroid injection followed by return to competition" }],
    correctAnswer: "C",
    explanation:
      "A compression-side (inferomedial) femoral neck stress fracture without a cortical break is typically managed conservatively with protected weight-bearing, activity modification, and close follow-up. Emergent fixation (A) is reserved for tension-side or displaced fractures. Continuing full training (B) or steroid injection then competing (D) risk progression. The tension-vs-compression distinction is what changes management.",
    cognitiveLevel: "apply",
  },
  {
    id: "hip-bones-occult-pre",
    domain: "hip-bones-stress",
    moduleId: "hip-bones-stress",
    prePostMapping: "parallel-pre",
    parallelId: "hip-occult-neck-fx",
    stem: "A 67-year-old woman with osteoporosis fell and has groin pain and inability to bear weight, but radiographs are read as negative. MRI shows an incomplete linear T1-hypointense fracture line with surrounding marrow edema in the femoral neck. What is the most appropriate management?",
    options: [{ key: "A", text: "Discharge home with full weight-bearing since radiographs were negative" }, { key: "B", text: "Provide a corticosteroid injection for presumed bursitis and mobilize" }, { key: "C", text: "Schedule routine outpatient physiotherapy with weight-bearing as tolerated" }, { key: "D", text: "Keep her non-weight-bearing and obtain urgent orthopedic referral for an occult femoral neck fracture" }],
    correctAnswer: "D",
    explanation:
      "An MRI-detected occult femoral neck fracture in an osteoporotic patient who cannot bear weight requires non-weight-bearing and urgent surgical referral because of the high risk of displacement. Discharging with full weight-bearing (A), steroid injection (B), or weight-bearing-as-tolerated physiotherapy (C) all risk fracture completion and displacement.",
    cognitiveLevel: "apply",
  },
  {
    id: "hip-bones-occult-post",
    domain: "hip-bones-stress",
    moduleId: "hip-bones-stress",
    prePostMapping: "parallel-post",
    parallelId: "hip-occult-neck-fx",
    stem: "An 82-year-old man fell from standing and has groin pain with inability to bear weight; two views of the hip are read as negative. MRI shows an incomplete T1-hypointense fracture line through the femoral neck with surrounding marrow edema and no displacement. What is the most appropriate management?",
    options: [{ key: "A", text: "Keep him non-weight-bearing and obtain urgent orthopedic referral for the occult femoral neck fracture" }, { key: "B", text: "Discharge with weight-bearing as tolerated because the plain films were negative" }, { key: "C", text: "Treat presumptively for greater trochanteric bursitis with a corticosteroid injection and mobilize" }, { key: "D", text: "Arrange routine outpatient physiotherapy with a follow-up radiograph in 6 weeks" }],
    correctAnswer: "A",
    explanation:
      "An MRI-detected occult femoral neck fracture in an older adult who cannot bear weight needs non-weight-bearing and urgent surgical referral because of the high risk of completion and displacement, even when radiographs are negative. Weight-bearing as tolerated (B), a steroid injection for presumed bursitis (C), or routine delayed physiotherapy (D) all risk the fracture completing and displacing.",
    cognitiveLevel: "apply",
  },
  {
    id: "hip-cartilage-oa-pre",
    domain: "hip-cartilage-oa",
    moduleId: "hip-cartilage-oa",
    prePostMapping: "parallel-pre",
    parallelId: "hip-cartilage-focal-vs-diffuse",
    stem: "A 48-year-old former athlete has groin pain. MRI shows DIFFUSE acetabular and femoral cartilage thinning with several subchondral cysts and global joint-space narrowing, rather than a single focal FAI rim lesion. The patient asks whether hip arthroscopy will fix the joint. Which interpretation best guides the management conversation?",
    options: [{ key: "A", text: "Diffuse cartilage loss with joint-space narrowing indicates early/established OA, shifting management away from arthroscopy toward joint-preservation/arthroplasty pathways" }, { key: "B", text: "The subchondral cysts represent an aggressive lytic tumor requiring biopsy before any treatment" }, { key: "C", text: "The findings are a focal FAI rim injury that arthroscopic labral repair will durably correct" }, { key: "D", text: "The pattern is transient bone marrow edema syndrome that will fully resolve with observation" }],
    correctAnswer: "A",
    explanation:
      "Diffuse bipolar cartilage loss with joint-space narrowing reflects OA, which predicts poor arthroscopic outcomes and pushes the conversation toward preservation or arthroplasty pathways. Subchondral geodes in OA are not aggressive tumors (B). The diffuse pattern is not a focal FAI rim lesion amenable to arthroscopy (C). OA with structural cartilage loss is not self-limited transient edema (D).",
    cognitiveLevel: "analyze",
  },
  {
    id: "hip-cartilage-oa-post",
    domain: "hip-cartilage-oa",
    moduleId: "hip-cartilage-oa",
    prePostMapping: "parallel-post",
    parallelId: "hip-cartilage-focal-vs-diffuse",
    stem: "A 52-year-old recreational cyclist has progressive groin pain. MRI demonstrates widespread bipolar cartilage thinning, multiple subchondral geodes, and superior joint-space narrowing, without a discrete focal rim lesion. The patient hopes arthroscopy will restore the joint. Which interpretation best frames the management discussion?",
    options: [{ key: "A", text: "The geodes are an aggressive lytic process mandating urgent oncologic biopsy" }, { key: "B", text: "This is an isolated focal chondral flap that arthroscopic debridement will permanently resolve" }, { key: "C", text: "Diffuse bipolar cartilage loss with joint-space narrowing represents OA, moving care toward arthroplasty rather than arthroscopic labral surgery" }, { key: "D", text: "This represents reversible transient marrow edema needing only rest" }],
    correctAnswer: "C",
    explanation:
      "Widespread bipolar cartilage loss with joint-space narrowing indicates OA; arthroscopy is poorly suited and the discussion shifts toward arthroplasty. OA geodes are not aggressive tumors (A). A diffuse process is not an isolated focal flap fixable by debridement (B), and structural OA cartilage loss is not reversible transient edema (D).",
    cognitiveLevel: "analyze",
  },
  {
    id: "hip-dont-miss-pre",
    domain: "hip-dont-miss",
    moduleId: "hip-dont-miss",
    prePostMapping: "parallel-pre",
    parallelId: "hip-dontmiss-avn-precollapse",
    stem: "A 58-year-old man on chronic corticosteroids has 6 weeks of groin pain and a normal radiograph. MRI shows a serpentine subchondral line in the anterosuperior femoral head with a 'double-line sign' and preserved spherical head contour without subchondral collapse. What management does this finding most appropriately drive?",
    options: [{ key: "A", text: "Reassure and discharge, since the head contour is preserved and no action is needed" }, { key: "B", text: "Treat as routine transient marrow edema with observation and full activity" }, { key: "C", text: "Refer to orthopedics for pre-collapse AVN, including protected weight-bearing and joint-preserving options" }, { key: "D", text: "Start antibiotics for presumed osteomyelitis based on the marrow signal" }],
    correctAnswer: "C",
    explanation:
      "A double-line sign with a serpentine subchondral line in a steroid-exposed patient is osteonecrosis (AVN); identifying it before collapse opens a window for protected weight-bearing and joint-preserving procedures, so referral is key. Discharge (A) or treating as transient edema (B) misses a progressive disease. There is no infectious picture to justify antibiotics (D).",
    cognitiveLevel: "analyze",
  },
  {
    id: "hip-dont-miss-post",
    domain: "hip-dont-miss",
    moduleId: "hip-dont-miss",
    prePostMapping: "parallel-post",
    parallelId: "hip-dontmiss-avn-precollapse",
    stem: "A 44-year-old woman with a history of heavy alcohol use has 2 months of groin pain and normal radiographs. MRI demonstrates a serpiginous subchondral 'double-line sign' in the superior femoral head with maintained sphericity and no subchondral fracture or flattening. What management does this finding most appropriately direct?",
    options: [{ key: "A", text: "Discharge with no follow-up because the femoral head remains spherical" }, { key: "B", text: "Manage as benign transient bone marrow edema with unrestricted activity" }, { key: "C", text: "Begin empiric IV antibiotics for suspected septic osteomyelitis" }, { key: "D", text: "Orthopedic referral for pre-collapse osteonecrosis with protected weight-bearing and joint-preserving consideration" }],
    correctAnswer: "D",
    explanation:
      "A double-line sign with maintained sphericity in an at-risk patient indicates pre-collapse AVN; catching it before collapse allows protected weight-bearing and joint-preserving surgery, so referral is appropriate. Discharge (A) or calling it transient edema (B) misses progressive necrosis. No infectious features justify antibiotics (C).",
    cognitiveLevel: "analyze",
  },
  {
    id: "hip-dontmiss-scfe-pre",
    domain: "hip-dont-miss",
    moduleId: "hip-dont-miss",
    prePostMapping: "parallel-pre",
    parallelId: "hip-scfe",
    stem: "A 13-year-old boy with obesity has 3 weeks of dull groin and knee pain and now walks with the foot externally rotated. MRI shows widening and irregularity of the proximal femoral physis with posteromedial slip of the epiphysis relative to the metaphysis. What is the most appropriate immediate management?",
    options: [{ key: "A", text: "Make him non-weight-bearing and arrange urgent orthopedic surgical referral" }, { key: "B", text: "Begin outpatient physical therapy and recheck in 6 weeks" }, { key: "C", text: "Allow full activity with NSAIDs and clinic follow-up in 3 months" }, { key: "D", text: "Inject the hip with corticosteroid and resume sports" }],
    correctAnswer: "A",
    explanation:
      "Physeal widening with posteromedial epiphyseal slip is a slipped capital femoral epiphysis (SCFE), which is an urgent, non-weight-bearing diagnosis requiring prompt surgical fixation to prevent further slip and AVN. Physical therapy (B), full activity (C), or steroid injection with return to sport (D) all risk progression and avascular necrosis.",
    cognitiveLevel: "apply",
  },
  {
    id: "hip-dontmiss-scfe-post",
    domain: "hip-dont-miss",
    moduleId: "hip-dont-miss",
    prePostMapping: "parallel-post",
    parallelId: "hip-scfe",
    stem: "An 11-year-old boy with obesity has several weeks of vague knee and thigh pain and now limps with the leg turned outward. MRI of the hips shows widening and irregularity of the proximal femoral physis with posteromedial displacement of the epiphysis. What is the most appropriate immediate management?",
    options: [{ key: "A", text: "Begin a knee-focused physiotherapy program and reassess in 6 weeks" }, { key: "B", text: "Allow unrestricted activity with NSAIDs and routine follow-up in 3 months" }, { key: "C", text: "Make him non-weight-bearing and obtain urgent orthopedic surgical referral" }, { key: "D", text: "Aspirate the knee to evaluate the referred knee pain" }],
    correctAnswer: "C",
    explanation:
      "Physeal widening with posteromedial epiphyseal displacement is a slipped capital femoral epiphysis (SCFE); referred knee and thigh pain is classic, and the diagnosis is missed when attention stays on the knee. It requires non-weight-bearing and prompt surgical fixation to prevent further slip and avascular necrosis. Knee physiotherapy (A), unrestricted activity (B), or knee aspiration (D) all delay fixation and risk progression and AVN.",
    cognitiveLevel: "apply",
  },
  {
    id: "hip-fai-labrum-pre",
    domain: "hip-fai-labrum",
    moduleId: "hip-fai-labrum",
    prePostMapping: "parallel-pre",
    parallelId: "hip-fai-chondral-weight",
    stem: "A 25-year-old hockey player has activity-related anterior groin pain. Dedicated hip MRI shows an alpha angle of 68 degrees on the oblique-axial neck plane, an anterosuperior labral tear, AND adjacent acetabular rim cartilage delamination. Conservative rehab has failed over 4 months. What does the imaging add that most supports operative referral over continued rehab?",
    options: [{ key: "A", text: "The 68-degree alpha angle alone proves symptomatic disease and mandates surgery regardless of cartilage" }, { key: "B", text: "The rim chondral delamination accompanying cam morphology and a labral tear weights toward arthroscopic referral" }, { key: "C", text: "The labral tear by itself indicates urgent same-week surgery to prevent dislocation" }, { key: "D", text: "The findings indicate diffuse end-stage OA, so arthroplasty rather than arthroscopy is appropriate" }],
    correctAnswer: "B",
    explanation:
      "Associated rim chondral injury/delamination alongside cam morphology and a labral tear is a feature that shifts decision-making toward arthroscopic surgery, especially after failed rehab. Cam morphology is common and often asymptomatic, so the alpha angle alone is not dispositive (A). A labral tear is not a dislocation emergency (C). Focal rim delamination is not diffuse end-stage OA requiring arthroplasty (D).",
    cognitiveLevel: "analyze",
  },
  {
    id: "hip-fai-labrum-post",
    domain: "hip-fai-labrum",
    moduleId: "hip-fai-labrum",
    prePostMapping: "parallel-post",
    parallelId: "hip-fai-chondral-weight",
    stem: "A 29-year-old dancer has deep flexion-provoked groin pain. Dedicated hip MRI shows an alpha angle of 64 degrees, an anterosuperior labral tear, and focal full-thickness acetabular rim cartilage loss with delamination at the same location, after 5 months of failed physiotherapy. Which imaging feature most strongly supports proceeding to arthroscopic referral rather than further conservative care?",
    options: [{ key: "A", text: "The 64-degree alpha angle alone confirms the pathology is symptomatic and dictates surgery" }, { key: "B", text: "The isolated labral tear mandates emergent operative repair within days" }, { key: "C", text: "The combination indicates global joint-space collapse warranting total hip arthroplasty" }, { key: "D", text: "The focal rim chondral delamination co-located with cam morphology and a labral tear favors surgical referral" }],
    correctAnswer: "D",
    explanation:
      "Co-located rim chondral delamination with cam morphology and a labral tear, after failed conservative care, weights toward arthroscopic referral. The alpha angle alone does not establish symptomatic disease because cam morphology is frequently asymptomatic (A). A labral tear is not an emergency (B). Focal rim loss is not global collapse requiring arthroplasty (C).",
    cognitiveLevel: "analyze",
  },
  {
    id: "hip-fai-cam-pre",
    domain: "hip-fai-labrum",
    moduleId: "hip-fai-labrum",
    prePostMapping: "parallel-pre",
    parallelId: "hip-cam-isolated",
    stem: "A 27-year-old with anterior groin pain has a dedicated hip MRI. On the oblique-axial plane along the femoral neck, the alpha angle measures 70 degrees with an anterosuperior osseous bump, but the labrum and cartilage are intact and the patient is currently asymptomatic at rest. How should this isolated finding influence management?",
    options: [{ key: "A", text: "Treat cam morphology as a common, often asymptomatic finding and correlate clinically rather than refer for surgery on imaging alone" }, { key: "B", text: "Refer for prophylactic arthroscopic osteoplasty because the alpha angle exceeds 55 degrees" }, { key: "C", text: "Order an urgent oncologic workup for the femoral neck osseous bump" }, { key: "D", text: "Place the patient non-weight-bearing for an impending femoral neck fracture" }],
    correctAnswer: "A",
    explanation:
      "Cam morphology is common and frequently asymptomatic. The historic >55-degree alpha-angle cutoff remains widely used, while ≥60 degrees is better supported for classification; neither threshold establishes symptomatic FAI. Isolated morphology without chondrolabral injury or concordant symptoms should be correlated clinically, not taken to surgery. Prophylactic osteoplasty on morphology alone (B) is not indicated. A cam bump is not a tumor (C) or a fracture (D).",
    cognitiveLevel: "analyze",
  },
  {
    id: "hip-fai-cam-post",
    domain: "hip-fai-labrum",
    moduleId: "hip-fai-labrum",
    prePostMapping: "parallel-post",
    parallelId: "hip-cam-isolated",
    stem: "A 32-year-old recreational swimmer has a dedicated hip MRI for lateral pain later attributed to the abductors. Incidentally, on the oblique-axial neck plane the alpha angle measures 66 degrees with an anterosuperior osseous bump, but the labrum and chondral surfaces are intact and there is no impingement-type pain with deep flexion. How should this isolated cam finding influence management?",
    options: [{ key: "A", text: "Refer for prophylactic arthroscopic osteoplasty because the alpha angle is above 55 degrees" }, { key: "B", text: "Treat cam morphology as a common, frequently asymptomatic finding and correlate clinically rather than operate on imaging alone" }, { key: "C", text: "Order a staging workup for an aggressive osseous lesion of the femoral neck" }, { key: "D", text: "Place the patient non-weight-bearing for an impending femoral neck fracture" }],
    correctAnswer: "B",
    explanation:
      "Cam morphology is common and frequently asymptomatic. The historic >55-degree alpha-angle cutoff remains widely used, while ≥60 degrees is better supported for classification; neither threshold establishes symptomatic FAI. An isolated bump without chondrolabral injury or concordant impingement symptoms should be correlated clinically, not taken to surgery — especially when found incidentally. Prophylactic osteoplasty on morphology alone (A) is not indicated; a cam bump is neither an aggressive osseous lesion (C) nor a fracture (D).",
    cognitiveLevel: "analyze",
  },
  {
    id: "hip-basics-pre",
    domain: "hip-mri-basics",
    moduleId: "hip-mri-basics",
    prePostMapping: "parallel-pre",
    parallelId: "hip-basics-fov-plane",
    stem: "A 24-year-old runner has deep anterior groin pain with pivoting. The ordered study is a large-FOV pelvis MRI read as 'no fracture, mild bursitis.' You suspect cam-type FAI and want to measure the alpha angle reliably. Which acquisition change most directly enables an accurate alpha-angle measurement to guide the FAI workup?",
    options: [{ key: "A", text: "Add a small-FOV dedicated hip protocol with an oblique-axial plane along the femoral neck" }, { key: "B", text: "Repeat the large-FOV pelvis sequence with thinner coronal slices only" }, { key: "C", text: "Add IV gadolinium to the existing large-FOV pelvis sequences" }, { key: "D", text: "Switch the large-FOV T1 sequences to STIR for better fat suppression" }],
    correctAnswer: "A",
    explanation:
      "Alpha angle requires an oblique-axial plane prescribed along the femoral neck on a dedicated small-FOV hip study; the large-FOV pelvis screen lacks the resolution and plane to measure cam morphology. Thinner coronal slices (B) still do not give the neck-axis plane needed. IV gadolinium (C) does not address geometry/resolution. STIR (D) changes contrast, not the plane or FOV needed for the measurement.",
    cognitiveLevel: "apply",
  },
  {
    id: "hip-basics-post",
    domain: "hip-mri-basics",
    moduleId: "hip-mri-basics",
    prePostMapping: "parallel-post",
    parallelId: "hip-basics-fov-plane",
    stem: "A 31-year-old soccer player has anterior hip pain catching with deep flexion. Outside imaging is a large-FOV pelvis MRI labeled 'unremarkable hips.' You want to confirm or exclude cam morphology before deciding on a surgical referral. Which protocol adjustment most directly provides the information needed to measure cam morphology?",
    options: [{ key: "A", text: "Order a small-FOV dedicated hip protocol including an oblique-axial plane along the femoral neck" }, { key: "B", text: "Re-run the large-FOV axial sequence with a larger matrix and the same coverage" }, { key: "C", text: "Convert the large-FOV PD sequences to chemically fat-saturated images" }, { key: "D", text: "Add post-contrast large-FOV imaging through both hips" }],
    correctAnswer: "A",
    explanation:
      "Cam morphology and the alpha angle are measured on a small-FOV dedicated hip protocol with an oblique-axial plane aligned to the femoral neck. A larger matrix on the large-FOV axial (B) still does not provide the neck-axis plane. Chemical fat-sat (C) changes contrast, not the plane/FOV. Contrast (D) adds nothing for measuring osseous cam shape.",
    cognitiveLevel: "apply",
  },
  {
    id: "hip-search-pre",
    domain: "hip-search-pattern",
    moduleId: "hip-search-pattern",
    prePostMapping: "parallel-pre",
    parallelId: "hip-search-tension-neck",
    stem: "A 40-year-old distance runner has worsening anterior groin pain, now with night pain and pain on weight-bearing. The reading radiologist anchors on an incidental small labral fray and stops. Given a fixed search-pattern discipline, which additional structure must be deliberately checked before translating the read into a return-to-run plan?",
    options: [{ key: "A", text: "The tension (superolateral) side of the femoral neck for a stress fracture line and marrow edema" }, { key: "B", text: "The contralateral asymptomatic acetabular labrum for incidental fraying" }, { key: "C", text: "The trochanteric bursa for fluid before scanning the femoral neck" }, { key: "D", text: "The skin and subcutaneous fat for postoperative seroma" }],
    correctAnswer: "A",
    explanation:
      "Satisfaction-of-search after spotting a minor labral fray risks missing a superolateral (tension-side) femoral neck stress fracture, which is a surgical-urgency finding that changes a runner from 'return to run' to non-weight-bearing and referral. The asymptomatic contralateral labrum (B), bursa first (C), or skin (D) do not carry the same management-changing red-flag weight in this presentation.",
    cognitiveLevel: "analyze",
  },
  {
    id: "hip-search-post",
    domain: "hip-search-pattern",
    moduleId: "hip-search-pattern",
    prePostMapping: "parallel-post",
    parallelId: "hip-search-tension-neck",
    stem: "A 22-year-old military recruit has 3 weeks of escalating groin pain after ramping up marching, now with rest pain. The MRI report fixates on a small herniation pit and concludes 'benign.' Applying a disciplined search pattern, which area most needs deliberate inspection before clearing the recruit to continue training?",
    options: [{ key: "A", text: "The opposite hip's herniation pit for symmetry" }, { key: "B", text: "The iliopsoas bursa for distension before assessing marrow" }, { key: "C", text: "The gluteal subcutaneous tissues for cellulitis" }, { key: "D", text: "The superolateral femoral neck for a tension-side stress fracture and reactive marrow edema" }],
    correctAnswer: "D",
    explanation:
      "Anchoring on a benign herniation pit can mask a tension-side (superolateral) femoral neck stress fracture in a high-risk recruit; finding it converts management to non-weight-bearing and urgent surgical referral. The contralateral pit (A), bursa first (B), or subcutaneous tissue (C) do not change this high-stakes decision the way the tension-side neck does.",
    cognitiveLevel: "analyze",
  },
  {
    id: "hip-tendons-pre",
    domain: "hip-tendons-muscles",
    moduleId: "hip-tendons-muscles",
    prePostMapping: "parallel-pre",
    parallelId: "hip-tendons-fullthickness-referral",
    stem: "A 70-year-old woman has chronic lateral hip pain, a limp, and weak abduction. MRI shows a FULL-THICKNESS gluteus medius tendon tear with 2 cm of tendon retraction and fatty muscle atrophy at the greater trochanter. Prior corticosteroid injection and physiotherapy failed. What does this imaging most appropriately direct?",
    options: [{ key: "A", text: "Another image-guided peritrochanteric corticosteroid injection as definitive treatment" }, { key: "B", text: "Reassurance that this is simple trochanteric bursitis managed with stretching" }, { key: "C", text: "Urgent escalation for suspected septic arthritis of the hip" }, { key: "D", text: "Orthopedic surgical referral for consideration of abductor tendon repair" }],
    correctAnswer: "D",
    explanation:
      "A full-thickness, retracted gluteus medius tear with atrophy that has failed conservative care warrants surgical referral for possible tendon repair. Repeat steroid injection (A) does not address a retracted full-thickness tear and may worsen tendon quality. This is not simple bursitis (B). There is no septic picture (C).",
    cognitiveLevel: "apply",
  },
  {
    id: "hip-tendons-post",
    domain: "hip-tendons-muscles",
    moduleId: "hip-tendons-muscles",
    prePostMapping: "parallel-post",
    parallelId: "hip-tendons-fullthickness-referral",
    stem: "A 64-year-old woman has persistent lateral hip pain and a Trendelenburg gait. MRI reveals a FULL-THICKNESS gluteus minimus and medius tendon tear with retraction and grade 2 fatty atrophy, after 6 months of physiotherapy and one peritrochanteric injection. What management does this imaging most appropriately support?",
    options: [{ key: "A", text: "Repeat peritrochanteric corticosteroid injection as the definitive next step" }, { key: "B", text: "Referral to orthopedic surgery to evaluate for abductor tendon reconstruction" }, { key: "C", text: "Labeling the process as greater trochanteric bursitis treated with a home program" }, { key: "D", text: "Emergent admission for presumed osteomyelitis of the trochanter" }],
    correctAnswer: "B",
    explanation:
      "A retracted full-thickness abductor tendon tear with fatty atrophy refractory to conservative measures should prompt surgical referral for possible reconstruction. Another injection (A) will not restore a retracted tendon. This is more than bursitis (C). No infectious findings are described to warrant osteomyelitis admission (D).",
    cognitiveLevel: "apply",
  },
  {
    id: "hip-tendons-hamstring-pre",
    domain: "hip-tendons-muscles",
    moduleId: "hip-tendons-muscles",
    prePostMapping: "parallel-pre",
    parallelId: "hip-hamstring-avulsion",
    stem: "A 45-year-old water-skier had a sudden hamstring 'pop' while the hip flexed and the knee extended. MRI shows all three proximal hamstring tendons avulsed from the ischial tuberosity with 3 cm of retraction and a surrounding hematoma. What is the most appropriate management?",
    options: [{ key: "A", text: "Provide a home stretching program and clear for return to sport in 2 weeks" }, { key: "B", text: "Refer promptly to orthopedic surgery for operative repair of the complete retracted avulsion" }, { key: "C", text: "Provide an image-guided corticosteroid injection at the ischial tuberosity" }, { key: "D", text: "Reassure as a grade 1 strain and continue normal activity" }],
    correctAnswer: "B",
    explanation:
      "A complete three-tendon proximal hamstring avulsion with significant (3 cm) retraction is a surgical lesion; timely referral is favored because the window for primary repair is best within a few weeks before further retraction and scarring. A stretching program with rapid return (A) or calling it a grade 1 strain (D) understages a complete avulsion. A corticosteroid injection (C) does not address tendon retraction and may impair healing.",
    cognitiveLevel: "apply",
  },
  {
    id: "hip-tendons-hamstring-post",
    domain: "hip-tendons-muscles",
    moduleId: "hip-tendons-muscles",
    prePostMapping: "parallel-post",
    parallelId: "hip-hamstring-avulsion",
    stem: "A 41-year-old man slipped on a boat ramp with the hip suddenly flexed and the knee held straight, feeling a painful pop in the buttock. MRI shows all three proximal hamstring tendons avulsed off the ischial tuberosity with 4 cm of retraction and a surrounding hematoma. What is the most appropriate management?",
    options: [{ key: "A", text: "Refer promptly to orthopedic surgery for operative repair of the complete retracted avulsion" }, { key: "B", text: "Prescribe a home eccentric-stretching program and clear for sport in 2 weeks" }, { key: "C", text: "Inject the ischial tuberosity with corticosteroid to control pain" }, { key: "D", text: "Reassure that this is a low-grade strain and continue normal activity" }],
    correctAnswer: "A",
    explanation:
      "A complete three-tendon proximal hamstring avulsion with significant (4 cm) retraction is a surgical lesion; prompt referral is favored because primary-repair outcomes are best within a few weeks before further retraction and scarring. A stretching program with early return (B) or calling it a low-grade strain (D) understages a complete avulsion. A corticosteroid injection (C) does not address tendon retraction and can impair healing.",
    cognitiveLevel: "apply",
  },
];
